Repository Fit-Links/FitLink-FE, pull requests merged in 2024-12, with the labels that each got.

#3 [#2] chore: ui 패키지 공통 디펜던시 설치
  packages/ui/package.json
  pnpm-lock.yaml
Labels: 📎chore

#6 [#5] chore: 루트의 하위 패키지 trainer, user 각 패키지의 빌드 및 개발 서버 실행을 실행 시킬 수 있는 script 작성
  package.json
Labels: 📎chore

#8 [#4/ui] feat: 디자인 토큰(색상) 및 유틸리티 설정
  docs/storybook/package.json
  docs/storybook/src/tailwind.css
  docs/storybook/stories/Colors.mdx
  packages/config-tailwind/globals.css
  packages/config-tailwind/package.json
  packages/config-tailwind/tailwind.config.ts
  packages/ui/package.json
  packages/ui/src/components/.gitkeep
  packages/ui/src/lib/utils.ts
  packages/ui/src/styles.css
  packages/ui/tailwind.config.ts
  pnpm-lock.yaml
Labels: ✨feat

#9 [#7/config-eslint] chore: 코딩 컨벤션에 명시된 룰 중, eslint로 설정할 수 있는 eslint rule 추가
  .github/pull_request_template.md
  apps/trainer/.eslintrc.json
  apps/user/.eslintrc.json
  packages/config-eslint/base.js
  packages/config-eslint/next.js
  packages/config-eslint/react-internal.js
Labels: 📎chore

#13 [#11/docs/storybook] fix: @5unwan/ui 패키지 스타일 버그 해결
  docs/storybook/package.json
  docs/storybook/tailwind.config.ts
  packages/config-tailwind/package.json
  packages/config-tailwind/variables.css
Labels: 🐛fix

#15 [#14/storybook] chore: @5unwan/storybook 패키지 빌드 결과 캐싱 및 gitignore 설정
  .gitignore
  docs/storybook/.gitignore
  pnpm-lock.yaml
  turbo.json
Labels: 📎chore

#12 [#10/config-tailwind] feat: 시스템 Typography 토큰화 적용
  docs/storybook/stories/FontSize.mdx
  package.json
  packages/config-tailwind/tailwind.config.ts
  turbo.json
Labels: ✨feat

#21 [#19/root] fix: 사용되지 않는 TailwindCSS 기본 설정 제거 및 누락된 TailwindCSS 기본 설정 추가
  docs/storybook/src/tailwind.css
  packages/config-tailwind/variables.css
  packages/ui/src/styles.css
Labels: 🐛fix

#23 [#20/config-tailwind] style: 색상 토큰 업데이트
  packages/config-tailwind/tailwind.config.ts
  packages/config-tailwind/variables.css
Labels: 💄style

#24 [#18/ui] feat: Input 공통 컴포넌트 구현
  docs/storybook/stories/Input.stories.tsx
  packages/ui/src/components/Input.tsx
  packages/ui/src/lib/utils.ts
Labels: ✨feat
