Repository Fit-Links/FitLink-FE, pull requests merged in 2025-05, with the labels that each got.

#140 [FLIZ-216/user] feat: 휴대폰 인증 로직 구현
  apps/trainer/app/my-page/my-information/edit-verificated-phone/_components/PhoneVerificationContainer.tsx
  apps/user/app/my-page/page.tsx
  apps/user/app/notification/_components/NotificationContainer.tsx
  apps/user/app/notification/_components/NotificationList.tsx
  apps/user/app/register/_components/RegisterFunnel.tsx
  apps/user/app/sns-verification/page.tsx
  apps/user/constants/routes.ts
  apps/user/middleware.ts
  apps/user/queries/auth.ts
  apps/user/services/auth.ts
  apps/user/services/types/auth.dto.ts
  apps/user/services/types/myInformation.dto.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/PhoneVerification/index.tsx
Labels: ✨feat

#136 [FLIZ-219/trainer] feat: 트레이너 도메인 고정 예약 변경 페이지로 이동 기능 구현
  apps/trainer/app/member-management/[memberId]/_components/MemberProfile.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
  apps/trainer/app/member-management/[memberId]/page.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/page.tsx
  apps/trainer/services/types/reservations.dto.ts
  packages/ui/src/components/NotificationItem/IconThumbnail.tsx
  packages/ui/src/components/PTPreference.tsx
Labels: ✨feat

#142 [FLIZ-230/root] ci: 포크 레포 커밋 싱크 워크플로우 작성
  .github/workflows/deploy_MaSeungHyun.yml
Labels: 📎chore

#143 [FLIZ-233/user] feat: 유저 도메인 로그인 플로우 완성
  apps/user/app/register/_components/RegisterFunnel.tsx
  apps/user/app/register/_components/ResultStep.tsx
  apps/user/app/register/_hooks/useFCMToken.ts
  apps/user/app/register/_hooks/useSignupForm.ts
  apps/user/app/sns-verification/page.tsx
  apps/user/components/Providers/index.tsx
  apps/user/middleware.ts
  apps/user/package.json
  apps/user/public/firebase-messaging-sw.js
  apps/user/services/notification.ts
  apps/user/services/types/notification.dto.ts
  packages/ui/src/components/PhoneVerification/index.tsx
  pnpm-lock.yaml
Labels: ✨feat

#144 [FLIZ-234/trainer] feat: 트레이너 도메인 로그인 플로우 완성
  apps/trainer/app/register/_components/RegisterFunnel.tsx
  apps/trainer/app/register/_components/ResultStep.tsx
  apps/trainer/app/register/_hooks/useFCMToken.ts
  apps/trainer/app/register/_hooks/useSaveTokenFromSearchParams.ts
  apps/trainer/app/register/_hooks/useSignupForm.ts
  apps/trainer/app/register/page.tsx
  apps/trainer/app/sns-verification/_components/ResultStep.tsx
  apps/trainer/app/sns-verification/_hooks/useSignupForm.ts
  apps/trainer/app/sns-verification/page.tsx
  apps/trainer/constants/route.ts
  apps/trainer/middleware.ts
  apps/trainer/package.json
  apps/trainer/public/firebase-messaging-sw.js
  apps/trainer/queries/auth.ts
  apps/trainer/services/auth.ts
  apps/trainer/services/notification.ts
  apps/trainer/services/types/auth.dto.ts
  apps/trainer/services/types/notification.dto.ts
  pnpm-lock.yaml
Labels: ✨feat

#145 [FLIZ-242/user] feat: 이미지 파일 업로드 로직 구현
  apps/user/app/register/_components/RegisterFunnel.tsx
  apps/user/services/attachment.ts
  apps/user/services/types/attachment.dto.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/FunnelSteps/BasicInfoStep.tsx
  packages/ui/src/components/ProfileImagePicker.tsx
Labels: ✨feat

#147 [FLIZ-247/core] feat: API 응답 에러 판별 로직 구현
  apps/trainer/app/register/_components/ResultStep.tsx
  apps/trainer/app/register/_hooks/useSignupForm.ts
  apps/trainer/types/index.d.ts
  apps/user/app/register/_components/ResultStep.tsx
  apps/user/app/register/_hooks/useSignupForm.ts
  apps/user/types/index.d.ts
  packages/core/src/api/core.ts
Labels: ✨feat

#148 [FLIZ-250/trainer] fix: PT 시간 설정 형식 오류 해결
  packages/ui/src/components/FunnelSteps/TrainerScheduleStep.tsx
Labels: 🐛fix

#149 [FLIZ-224/user] feat: 유저 마이페이지 API 작업
  apps/user/app/my-page/_components/BottomSheet/EditPreferredScheduleBottomSheet.tsx
  apps/user/app/my-page/_components/Header.tsx
  apps/user/app/my-page/_components/LogoutButton.tsx
  apps/user/app/my-page/_components/MyPageContainer.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContext.ts
  apps/user/app/my-page/_components/PTHistory/PTHistoryFilter.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryProvider.tsx
  apps/user/app/my-page/_components/PTInformation/ConnectedTrainerItem.tsx
  apps/user/app/my-page/_components/PTInformation/ScheduleContainer.tsx
  apps/user/app/my-page/_components/PTInformation/ScheduleInformation.tsx
  apps/user/app/my-page/_components/PTInformation/ScheduleInformationItem.tsx
  apps/user/app/my-page/_components/ProfileHeader.tsx
  apps/user/app/my-page/connect-trainer/_components/ConnectTrainerContainer.tsx
  apps/user/app/my-page/connect-trainer/_components/InputOTP/index.tsx
  apps/user/app/my-page/connect-trainer/page.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/BottomSheet/SuccessEditPreferenceTimeBottomSheet.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/EditPreferenceTimeContainer.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/PreferenceTimePicker.tsx
  apps/user/app/my-page/edit-workout-schedules/page.tsx
  apps/user/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/user/app/my-page/my-information/_components/Fallback.tsx
  apps/user/app/my-page/my-information/_components/MemorizedChangePhoneLink.tsx
  apps/user/app/my-page/my-information/_components/MyDetailInformations.tsx
  apps/user/app/my-page/my-information/_components/MyInformationAvatar.tsx
  apps/user/app/my-page/my-information/_components/ProfileImage.tsx
  apps/user/app/my-page/my-information/_utils/format.ts
  apps/user/app/my-page/my-information/page.tsx
  apps/user/app/my-page/my-information/verify-phone/_components/VerificationPhoneContainer.tsx
  apps/user/app/my-page/my-information/verify-phone/page.tsx
  apps/user/app/my-page/my-trainer-information/_components/BottomSheet/UnlinkAlarmSheet.tsx
  apps/user/app/my-page/my-trainer-information/_components/MyTrainerInformationContainer.tsx
  apps/user/app/my-page/my-trainer-information/_components/TrainerUnlinkItem.tsx
  apps/user/app/my-page/my-trainer-information/page.tsx
  apps/user/app/my-page/page.tsx
  apps/user/components/SheetItem.tsx
  apps/user/constants/Day.ts
  apps/user/package.json
  apps/user/queries/myInformation.ts
  apps/user/services/myInformation.ts
  apps/user/services/types/myInformation.dto.ts
  apps/user/utils/schedule.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/PhoneVerification/PhoneVerificationButton.tsx
  pnpm-lock.yaml
Labels: ✨feat

#150 [FLIZ-257] fix. 빌드 에러 해결
  apps/user/app/my-page/_components/MyPageContainer.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx
  apps/user/app/my-page/my-information/page.tsx
  apps/user/app/my-page/my-trainer-information/_components/MyTrainerInformationContainer.tsx
  apps/user/app/my-page/my-trainer-information/page.tsx
  apps/user/app/my-page/page.tsx
Labels: 🐛fix

#151 [FLIZ-183/user] feat: 유저 서비스 알림 페이지 API 연결
  apps/user/app/layout.tsx
  apps/user/app/notification/_components/EmptyList.tsx
  apps/user/app/notification/_components/NotificationContainer.tsx
  apps/user/app/notification/_components/NotificationList.tsx
  apps/user/components/BottomNavigation.tsx
  apps/user/components/Providers/FooterProvider.tsx
  apps/user/hooks/useIntersectionObserver.ts
  apps/user/queries/notification.ts
  apps/user/services/notification.ts
  apps/user/services/types/notification.dto.ts
  packages/core/src/utils/throttle.ts
Labels: ✨feat

#152 [FLIZ-255/trainer] feat: 트레이너 도메인 PWA 설정
  apps/trainer/.gitignore
  apps/trainer/app/layout.tsx
  apps/trainer/components/PWAManifestLinks.tsx
  apps/trainer/next.config.mjs
  apps/trainer/package.json
  apps/trainer/public/icon512_maskable.png
  apps/trainer/public/icon512_rounded.png
  apps/trainer/public/manifest.json
  apps/trainer/public/splash_screens/10.2__iPad_landscape.png
  apps/trainer/public/splash_screens/10.2__iPad_portrait.png
  apps/trainer/public/splash_screens/10.5__iPad_Air_landscape.png
  apps/trainer/public/splash_screens/10.5__iPad_Air_portrait.png
  apps/trainer/public/splash_screens/10.9__iPad_Air_landscape.png
  apps/trainer/public/splash_screens/10.9__iPad_Air_portrait.png
  apps/trainer/public/splash_screens/11__iPad_Pro_M4_landscape.png
  apps/trainer/public/splash_screens/11__iPad_Pro_M4_portrait.png
  apps/trainer/public/splash_screens/11__iPad_Pro__10.5__iPad_Pro_landscape.png
  apps/trainer/public/splash_screens/11__iPad_Pro__10.5__iPad_Pro_portrait.png
  apps/trainer/public/splash_screens/12.9__iPad_Pro_landscape.png
  apps/trainer/public/splash_screens/12.9__iPad_Pro_portrait.png
  apps/trainer/public/splash_screens/13__iPad_Pro_M4_landscape.png
  apps/trainer/public/splash_screens/13__iPad_Pro_M4_portrait.png
  apps/trainer/public/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_landscape.png
  apps/trainer/public/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
  apps/trainer/public/splash_screens/8.3__iPad_Mini_landscape.png
  apps/trainer/public/splash_screens/8.3__iPad_Mini_portrait.png
  apps/trainer/public/splash_screens/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_landscape.png
  apps/trainer/public/splash_screens/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_portrait.png
  apps/trainer/public/splash_screens/iPhone_11_Pro_Max__iPhone_XS_Max_landscape.png
  apps/trainer/public/splash_screens/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  apps/trainer/public/splash_screens/iPhone_11__iPhone_XR_landscape.png
  apps/trainer/public/splash_screens/iPhone_11__iPhone_XR_portrait.png
  apps/trainer/public/splash_screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_landscape.png
  apps/trainer/public/splash_screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  apps/trainer/public/splash_screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_landscape.png
  apps/trainer/public/splash_screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  apps/trainer/public/splash_screens/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_landscape.png
  apps/trainer/public/splash_screens/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_portrait.png
  apps/trainer/public/splash_screens/iPhone_16_Pro_Max_landscape.png
  apps/trainer/public/splash_screens/iPhone_16_Pro_Max_portrait.png
  apps/trainer/public/splash_screens/iPhone_16_Pro_landscape.png
  apps/trainer/public/splash_screens/iPhone_16_Pro_portrait.png
  apps/trainer/public/splash_screens/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_landscape.png
  apps/trainer/public/splash_screens/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_portrait.png
  apps/trainer/public/splash_screens/iPhone_16e__iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_landscape.png
  apps/trainer/public/splash_screens/iPhone_16e__iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  apps/trainer/public/splash_screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_landscape.png
  apps/trainer/public/splash_screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  apps/trainer/public/splash_screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_landscape.png
  apps/trainer/public/splash_screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  apps/trainer/public/splash_screens/icon.png
  pnpm-lock.yaml
Labels: ✨feat

#154 [FLIZ-260/trainer] feat: 회원가입 완료 후 토큰 최신화 로직 추가
  apps/trainer/app/api/auth/tokens/route.ts
  apps/trainer/app/register/_components/ResultStep.tsx
  apps/trainer/services/auth.ts
  apps/trainer/services/types/auth.dto.ts
Labels: ✨feat

#155 [FLIZ-261/user] feat: 회원가입 완료 후 토큰 최신화 로직 추가
  apps/user/app/api/auth/tokens/route.ts
  apps/user/app/register/_components/ResultStep.tsx
  apps/user/services/auth.ts
  apps/user/services/types/auth.dto.ts
Labels: ✨feat

#156 [FLIZ-264/user, trainer] feat: BottomNavigation 라우팅 로직 추가
  apps/trainer/components/BottomNavigation.tsx
  apps/trainer/components/Providers/FooterProvider.tsx
  apps/trainer/constants/route.ts
  apps/user/components/BottomNavigation.tsx
  apps/user/components/Providers/FooterProvider.tsx
Labels: ✨feat

#153 [FLIZ-254/user] feat: 유저 도메인 PWA 설정
  apps/user/.gitignore
  apps/user/PWAManifestLinks.tsx
  apps/user/app/layout.tsx
  apps/user/next.config.mjs
  apps/user/package.json
  apps/user/public/icon512_maskable.png
  apps/user/public/icon512_rounded.png
  apps/user/public/manifest.json
  apps/user/public/splash_screens/10.2__iPad_landscape.png
  apps/user/public/splash_screens/10.2__iPad_portrait.png
  apps/user/public/splash_screens/10.5__iPad_Air_landscape.png
  apps/user/public/splash_screens/10.5__iPad_Air_portrait.png
  apps/user/public/splash_screens/10.9__iPad_Air_landscape.png
  apps/user/public/splash_screens/10.9__iPad_Air_portrait.png
  apps/user/public/splash_screens/11__iPad_Pro_M4_landscape.png
  apps/user/public/splash_screens/11__iPad_Pro_M4_portrait.png
  apps/user/public/splash_screens/11__iPad_Pro__10.5__iPad_Pro_landscape.png
  apps/user/public/splash_screens/11__iPad_Pro__10.5__iPad_Pro_portrait.png
  apps/user/public/splash_screens/12.9__iPad_Pro_landscape.png
  apps/user/public/splash_screens/12.9__iPad_Pro_portrait.png
  apps/user/public/splash_screens/13__iPad_Pro_M4_landscape.png
  apps/user/public/splash_screens/13__iPad_Pro_M4_portrait.png
  apps/user/public/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_landscape.png
  apps/user/public/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
  apps/user/public/splash_screens/8.3__iPad_Mini_landscape.png
  apps/user/public/splash_screens/8.3__iPad_Mini_portrait.png
  apps/user/public/splash_screens/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_landscape.png
  apps/user/public/splash_screens/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_portrait.png
  apps/user/public/splash_screens/iPhone_11_Pro_Max__iPhone_XS_Max_landscape.png
  apps/user/public/splash_screens/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  apps/user/public/splash_screens/iPhone_11__iPhone_XR_landscape.png
  apps/user/public/splash_screens/iPhone_11__iPhone_XR_portrait.png
  apps/user/public/splash_screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_landscape.png
  apps/user/public/splash_screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  apps/user/public/splash_screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_landscape.png
  apps/user/public/splash_screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  apps/user/public/splash_screens/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_landscape.png
  apps/user/public/splash_screens/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_portrait.png
  apps/user/public/splash_screens/iPhone_16_Pro_Max_landscape.png
  apps/user/public/splash_screens/iPhone_16_Pro_Max_portrait.png
  apps/user/public/splash_screens/iPhone_16_Pro_landscape.png
  apps/user/public/splash_screens/iPhone_16_Pro_portrait.png
  apps/user/public/splash_screens/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_landscape.png
  apps/user/public/splash_screens/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_portrait.png
  apps/user/public/splash_screens/iPhone_16e__iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_landscape.png
  apps/user/public/splash_screens/iPhone_16e__iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  apps/user/public/splash_screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_landscape.png
  apps/user/public/splash_screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  apps/user/public/splash_screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_landscape.png
  apps/user/public/splash_screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  apps/user/public/splash_screens/icon.png
  pnpm-lock.yaml
Labels: ✨feat

#157 [FLIZ-209/user] feat: 유저 도메인 API 작업
  apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
  apps/trainer/app/schedule-management/_components/Calendar/index.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/index.tsx
  apps/trainer/app/schedule-management/_constants/reservationConfig.ts
  apps/trainer/app/schedule-management/_libs/CalendarUtils.ts
  apps/user/app/notification/page.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
  apps/user/app/schedule-management/_components/Calendar/WeekCell.tsx
  apps/user/app/schedule-management/_components/Calendar/WeekRow.tsx
  apps/user/app/schedule-management/_components/Calendar/index.tsx
  apps/user/app/schedule-management/_components/ReservationAdder.tsx
  apps/user/app/schedule-management/_hooks/mutation/useReservationCancelMutation.ts
  apps/user/app/schedule-management/_utils/reservationMerger.ts
  apps/user/app/schedule-management/page.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
  apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationChangeMutation.ts
  apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationRequestMutation.ts
  apps/user/app/schedule-management/reservation/[mode]/page.tsx
  apps/user/constants/routes.ts
  apps/user/middleware.ts
  apps/user/queries/myInformation.ts
  apps/user/services/myInformation.ts
  apps/user/services/reservations.ts
  apps/user/services/types/myInformation.dto.ts
  apps/user/services/types/reservations.dto.ts
  packages/core/src/api/types/common.ts
Labels: ✨feat

#158 [FLIZ-248/trainer] feat: 트레이너 서비스 알림 페이지 API 연결
  apps/trainer/app/notification/_components/EmptyList.tsx
  apps/trainer/app/notification/_components/NotificationContainer.tsx
  apps/trainer/app/notification/_components/NotificationItemContainer.tsx
  apps/trainer/app/notification/_components/NotificationItemError.tsx
  apps/trainer/app/notification/_components/NotificationItemFallback.tsx
  apps/trainer/app/notification/_components/NotificationListFallback.tsx
  apps/trainer/app/notification/_components/NotificationSearch/EmptySearchResult.tsx
  apps/trainer/app/notification/_components/NotificationSearch/MemberNotificationResult.tsx
  apps/trainer/app/notification/_components/NotificationSearch/index.tsx
  apps/trainer/app/notification/_components/ProfileCardFallback.tsx
  apps/trainer/app/notification/_components/ProfileCardListFallback.tsx
  apps/trainer/app/notification/_components/SessionSetterSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SheetErrorFallback.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SheetFallback.tsx
  apps/trainer/app/notification/_types/index.ts
  apps/trainer/app/notification/_utils/createFilteredNotificationCount.ts
  apps/trainer/app/notification/_utils/handleNotificationFilter.ts
  apps/trainer/app/notification/page.tsx
  apps/trainer/app/schedule-management/_components/Calendar/index.tsx
  apps/trainer/app/schedule-management/_libs/CalendarUtils.ts
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/ApproveButton.tsx
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/MemberCardList.tsx
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
  apps/trainer/components/QueryErrorBoundary.tsx
  apps/trainer/hooks/useDebounce.ts
  apps/trainer/hooks/useIntersectionObserver.ts
  apps/trainer/package.json
  apps/trainer/queries/notification.ts
  apps/trainer/queries/reservation.ts
  apps/trainer/queries/userManagement.ts
  apps/trainer/services/notification.ts
  apps/trainer/services/reservations.ts
  apps/trainer/services/types/notification.dto.ts
  apps/trainer/services/types/reservations.dto.ts
  apps/trainer/services/types/userManagement.dto.ts
  apps/trainer/services/userManagement.ts
  apps/user/app/notification/_components/NotificationContainer.tsx
  packages/core/src/utils/debounce.ts
  pnpm-lock.yaml
Labels: ✨feat

#159 [FLIZ-273/user] feat: 유저 마이페이지 API 연결 (PT 히스토리, 수업 희망시간 변경, 프로필 사진)
  apps/trainer/app/member-management/[memberId]/_components/MemberProfile.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
  apps/trainer/app/member-management/[memberId]/page.tsx
  apps/trainer/app/my-page/page.tsx
  apps/user/app/my-page/_components/BottomSheet/EditPreferredScheduleBottomSheet.tsx
  apps/user/app/my-page/_components/MyPageContainer.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContext.ts
  apps/user/app/my-page/_components/PTHistory/PTHistoryCotainer.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryFilter.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryProvider.tsx
  apps/user/app/my-page/_components/PTHistory/_store/PTHistoryFilterStore.ts
  apps/user/app/my-page/_components/PTInformation/ConnectedTrainerItem.tsx
  apps/user/app/my-page/_utils/ preferredTime.ts
  apps/user/app/my-page/_utils/getPhoneNumberFormat.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/EditPreferenceTimeContainer.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/PreferenceTimePicker.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/PreferredTimeForm.tsx
  apps/user/app/my-page/edit-workout-schedules/page.tsx
  apps/user/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/user/app/my-page/my-information/_components/MyDetailInformations.tsx
  apps/user/app/my-page/my-information/_components/MyInformationAvatar.tsx
  apps/user/app/my-page/my-information/_utils/format.ts
  apps/user/app/my-page/my-information/page.tsx
  apps/user/app/my-page/my-trainer-information/_components/MyTrainerInformationContainer.tsx
  apps/user/app/my-page/page.tsx
  apps/user/queries/myInformation.ts
  apps/user/services/myInformation.ts
  apps/user/services/types/myInformation.dto.ts
  docs/storybook/stories/PTPreference.stories.tsx
  docs/storybook/stories/trainer/PTSchedule.stories.tsx
  packages/core/src/api/types/common.ts
  packages/ui/src/components/PTHistoryItem.tsx
  packages/ui/src/utils/makeWeekSchedule.ts
Labels: ✨feat

#160 [FLIZ-225] feat: 트레이너 마이페이지 API 연결
  apps/trainer/app/my-page/_components/EditScheduleBottomSheet.tsx
  apps/trainer/app/my-page/_components/LogoutButton.tsx
  apps/trainer/app/my-page/_components/MyAvailableTimeContainer.tsx
  apps/trainer/app/my-page/_components/MyDayOffContainer.tsx
  apps/trainer/app/my-page/_components/MyPageContainer.tsx
  apps/trainer/app/my-page/_components/ProfileItemForRouting.tsx
  apps/trainer/app/my-page/_components/ScheduleInformation.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleApplyAtStep/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleFunnel.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleStep/index.tsx
  apps/trainer/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/trainer/app/my-page/my-information/_components/BottomSheet/SheetItem.tsx
  apps/trainer/app/my-page/my-information/_components/EditProfileButton.tsx
  apps/trainer/app/my-page/my-information/_components/MyInformationContainer.tsx
  apps/trainer/app/my-page/my-information/_utils/getFormattedPhoneNumber.tsx
  apps/trainer/app/my-page/my-information/page.tsx
  apps/trainer/app/my-page/page.tsx
  apps/trainer/app/my-page/trainer-code/_components/TrainerCodeContainer/InputWithCopy.tsx
  apps/trainer/app/my-page/trainer-code/_components/TrainerCodeContainer/index.tsx
  apps/trainer/app/my-page/trainer-code/page.tsx
  apps/trainer/components/PTSchedule.tsx
  apps/trainer/queries/myInformation.ts
  apps/trainer/services/myInformation.ts
  apps/trainer/services/types/myInformation.dto.ts
  apps/trainer/utils/avaliableScheduleUtils.ts
  docs/storybook/stories/trainer/PTSchedule.stories.tsx
  packages/ui/src/components/PhoneVerification/index.tsx
Labels: ✨feat

#165 [FLIZ-241/trainer] feat: MemberManagementContainer API 연결
  apps/trainer/app/member-management/_components/MemberManagementContainer/MemberProfileList.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtRemainingCountEditSheet.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtTotalCountEditSheet.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/index.tsx
  apps/trainer/app/member-management/_components/MemberProfileListFallback.tsx
  apps/trainer/app/notification/_components/NotificationSearch/index.tsx
  apps/trainer/components/EmptySearchResult.tsx
  apps/trainer/hoc/WithBottomSheetStepper.tsx
  apps/trainer/services/types/userManagement.dto.ts
Labels: ✨feat

#166 [FLIZ-277] feat: 유저 프로젝트 진입 페이지 splash 및 유저 상태에 따른 라우팅 기능 구현
  apps/user/app/page.tsx
  apps/user/components/Providers/FooterProvider.tsx
  apps/user/components/Splash.tsx
  apps/user/public/splash_screens/web_splash_icon.avif
  apps/user/services/auth.ts
  apps/user/services/types/auth.dto.ts
Labels: ✨feat

#169 [FLIZ-263/user] feat: authorization 로직 구현
  apps/user/app/api/auth/reissue-token/route.ts
  apps/user/app/apiCore.ts
  apps/user/app/my-page/layout.tsx
  apps/user/app/notification/layout.tsx
  apps/user/app/refresh-session/loading.tsx
  apps/user/app/refresh-session/page.tsx
  apps/user/app/schedule-management/layout.tsx
  apps/user/constants/url.ts
  apps/user/middleware.ts
  apps/user/middleware/handlers/handleProtectedRoute.ts
  apps/user/middleware/handlers/handleTokenFromUrl.ts
  apps/user/middleware/utils/routeMatchers.ts
  apps/user/services/auth.ts
  apps/user/services/types/auth.dto.ts
  apps/user/utils/auth.ts
  apps/user/utils/token.ts
Labels: ✨feat

#170 [FLIZ-286/trainer] fix: refresh-session 페이지 prerender 에러 해결
  apps/trainer/app/refresh-session/loading.tsx
Labels: 🐛fix

#172 [FLIZ-285/trainer] feat: 트레이너 알림 action sheet 및 하위 페이지 API 연결
  apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
  apps/trainer/app/notification/connect/page.tsx
  apps/trainer/app/notification/disconnect/page.tsx
  apps/trainer/app/notification/page.tsx
  apps/trainer/app/notification/reservation-edit/page.tsx
  apps/trainer/app/notification/reservation/page.tsx
  apps/trainer/app/notification/session/page.tsx
  apps/trainer/components/NotificationAccordion.tsx
  apps/trainer/constants/route.ts
  apps/trainer/queries/userManagement.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/Header.tsx
Labels: ✨feat

#175 [FLIZ-284] feat: 유저 마이페이지 Suspense 및 ErrorBoundary 작업
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
  apps/user/app/my-page/_components/MyPageContainer.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryCotainer.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryFilter.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryLabel.tsx
  apps/user/app/my-page/_components/PTHistory/_store/PTHistoryFilterStore.ts
  apps/user/app/my-page/_components/PTInformation/ConnectedTrainerItem.tsx
  apps/user/app/my-page/_components/Skeleton/MyPageHistorySkeleton.tsx
  apps/user/app/my-page/_components/Skeleton/MyPageItemSkeleton.tsx
  apps/user/app/my-page/_components/Skeleton/index.tsx
  apps/user/app/my-page/connect-trainer/_components/InputOTP/index.tsx
  apps/user/app/my-page/my-information/_components/Fallback.tsx
  apps/user/app/my-page/my-information/_components/MyDetailInformations.tsx
  apps/user/app/my-page/my-information/_components/MyInformationAvatar.tsx
  apps/user/app/my-page/my-information/_components/Skeleton/SkeletonItem.tsx
  apps/user/app/my-page/my-information/_components/Skeleton/index.tsx
  apps/user/app/my-page/my-information/page.tsx
  apps/user/app/my-page/my-trainer-information/_components/MyTrainerInformationContainer.tsx
  apps/user/app/my-page/my-trainer-information/_components/Skeleton/index.tsx
  apps/user/app/my-page/my-trainer-information/page.tsx
  apps/user/app/my-page/page.tsx
  apps/user/components/QueryErrorFallback/ErrorFallback.tsx
  apps/user/components/QueryErrorFallback/index.tsx
  packages/ui/src/components/GlobalFallback.tsx
  packages/ui/src/components/PTHistoryItem.tsx
Labels: ✨feat

#176 [FLIZ-292/ui] fix: Sheet slide animation 버그 해결
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/MemberProfileList.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtRemainingCountEditSheet.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtTotalCountEditSheet.tsx
  apps/trainer/app/my-page/_components/EditScheduleBottomSheet.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/ScheduleChangeResultSheet.tsx
  apps/trainer/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/trainer/app/notification/_components/SessionSetterSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationControlSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationNotAllowedCancelSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx
  apps/trainer/app/schedule-management/_components/ScheduleBottomSheet.tsx
  apps/trainer/app/schedule-management/_components/TimeOptionList.tsx
  apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/DayoffAdderButton.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/FixedReservationAdderButton.tsx
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/ApproveButton.tsx
  apps/user/app/my-page/_components/BottomSheet/EditPreferredScheduleBottomSheet.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/BottomSheet/SuccessEditPreferenceTimeBottomSheet.tsx
  apps/user/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/user/app/my-page/my-trainer-information/_components/BottomSheet/UnlinkAlarmSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/RequestSuccessSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
Labels: 🐛fix

#177 [FLIZ-294] fix: 트레이너 수업 시간 변경 이슈 해결
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleApplyAtStep/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
  apps/trainer/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/trainer/utils/avaliableScheduleUtils.ts
  apps/user/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
Labels: 🐛fix
