Repository Fit-Links/FitLink-FE, pull requests merged in 2025-04, with the labels that each got.

#114 [FLIZ-182/root] ci: 서비스 배포 fork repository ci/cd 변경
  .github/workflows/deploy.yml
Labels: 👷ci

#104 [FLIZ-121/trainer] feat: 유저 도메인 일정관리/예약 페이지 구현
  apps/user/app/schedule-management/_components/BottomSheet/RequestSuccessSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
  apps/user/app/schedule-management/_components/Calendar/Header.tsx
  apps/user/app/schedule-management/_components/Calendar/WeekCell.tsx
  apps/user/app/schedule-management/_components/Calendar/WeekRow.tsx
  apps/user/app/schedule-management/_components/Calendar/index.tsx
  apps/user/app/schedule-management/_components/ReservationAdder.tsx
  apps/user/app/schedule-management/_constants/route.ts
  apps/user/app/schedule-management/_libs/checkReservationIsFuture.ts
  apps/user/app/schedule-management/_types/addReservation.ts
  apps/user/app/schedule-management/_utils/resolveTrainerConnectionFlow.ts
  apps/user/app/schedule-management/page.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/Header.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/TwoWeekCalendar.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
  apps/user/app/schedule-management/reservation/[mode]/page.tsx
  apps/user/app/schedule-management/reservation/[mode]/types/requestReservation.ts
  apps/user/components/Calendar/WeekRow.tsx
  apps/user/components/Calendar/index.tsx
  apps/user/components/Providers/FooterProvider.tsx
  apps/user/components/Providers/index.tsx
  apps/user/constants/.gitkeep
  apps/user/package.json
  apps/user/services/types/myInformation.dto.ts
  apps/user/tailwind.config.ts
  docs/storybook/stories/DayPicker.stories.tsx
  packages/core/src/api/core.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/DayOfTwoWeekPicker.tsx
  packages/ui/src/components/DayPicker/Caption.tsx
  packages/ui/src/components/DayPicker/index.tsx
  packages/ui/src/components/TimeCellToggleGroup.tsx
  packages/ui/src/components/variants/withNotification.ts
  pnpm-lock.yaml
Labels: ✨feat

#117 [FLIZ-193/root] chore: root의 build.sh에서 기존에 output 폴더를 제거하던 로직 제거
  build.sh
Labels: 📎chore

#119 [FLIZ-196/fix] root: cicd 액션 실행시 개인 리포지토리로 숨김 파일은 제거되고 clone 되는 에러 수정
  build.sh
Labels: 🐛fix

#121 [FLIZ-198/root] fix: build.sh, deploy.yml 수정했던 로직들 모두 rollback
  .github/workflows/deploy.yml
  build.sh
Labels: 🐛fix

#122 [FLIZ-202/root] fix: origin 레포의 모든 파일 및 폴더를 개인 레포에 복사하도록 build.sh 수정
  build.sh
Labels: 🐛fix

#123 [FLIZ-203/ui] fix: ProfileItem 컴포넌트의 icon props의 타입 불일치로 발생하는 eslint 에러 수정
  packages/ui/src/components/ProfileItem.tsx
Labels: 🐛fix

#124 [FLIZ-204/root] chore: vercel이 터보레포의 환경 변수를 이해할 수 있도록 turbo.json의 globalEnv에 환경 변수 네이밍 추가
  turbo.json
Labels: 📎chore

#125 [FLIZ-205/docs] fix: 스토리북의 user/Calendar 스토리의 잘못된 import 경로 수정
  docs/storybook/stories/user/Calendar.stories.tsx
Labels: 🐛fix

#115 [FLIZ-187/root/feat] feat: 휴대폰 인증 공통 컴포넌트 구현
  packages/ui/src/assets/verify-phone.avif
  packages/ui/src/components/PhoneVerification/PhoneVerificationButton.tsx
  packages/ui/src/components/PhoneVerification/PhoneVerificationGuide.tsx
  packages/ui/src/components/PhoneVerification/PhoneVerificationImage.tsx
  packages/ui/src/components/PhoneVerification/PhoneVerificationNotice.tsx
  packages/ui/src/components/PhoneVerification/index.tsx
  packages/ui/src/types/image.d.ts
  packages/ui/tsconfig.json
Labels: ✨feat

#126 [FLIZ-184/trainer] feat: 로그인 페이지 구현
  apps/trainer/app/layout.tsx
  apps/trainer/app/login/_components/LoginButton/GoogleContent.tsx
  apps/trainer/app/login/_components/LoginButton/KakaoContent.tsx
  apps/trainer/app/login/_components/LoginButton/NaverContent.tsx
  apps/trainer/app/login/_components/LoginButton/index.tsx
  apps/trainer/app/login/page.tsx
  apps/trainer/app/sns-verification/_components/RegisterFunnel.tsx
  apps/trainer/app/sns-verification/_components/ResultStep.tsx
  apps/trainer/app/sns-verification/_hooks/useSaveTokenFromSearchParams.ts
  apps/trainer/app/sns-verification/_hooks/useSignupForm.ts
  apps/trainer/app/sns-verification/page.tsx
  apps/trainer/components/Providers/FooterProvider.tsx
  apps/trainer/components/Providers/index.tsx
  apps/trainer/constants/loginButton.ts
  apps/trainer/constants/token.ts
  apps/trainer/constants/url.ts
  apps/trainer/package.json
  apps/trainer/public/google_logo.png
  apps/trainer/public/kakao_logo.png
  apps/trainer/public/naver_logo.png
  apps/trainer/services/auth.ts
  apps/trainer/services/core.ts
  apps/trainer/tailwind.config.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/FunnelSteps/TrainerScheduleStep.tsx
  packages/ui/src/components/FunnelSteps/WorkoutScheduleStep.tsx
  pnpm-lock.yaml
Labels: ✨feat

#116 [FLIZ-170/trainer] feat: 트레이너 도메인 일정관리/예약 페이지 구현
  apps/trainer/app/schedule-management/_components/Calendar/DayColumn.tsx
  apps/trainer/app/schedule-management/_components/Calendar/DayOfWeek.tsx
  apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
  apps/trainer/app/schedule-management/_components/Calendar/TimeColumn.tsx
  apps/trainer/app/schedule-management/_components/Calendar/WeekRow.tsx
  apps/trainer/app/schedule-management/_components/Calendar/index.tsx
  apps/trainer/app/schedule-management/_components/MemberListContainer/MemberCardList.tsx
  apps/trainer/app/schedule-management/_components/MemberListContainer/SearchBar.tsx
  apps/trainer/app/schedule-management/_components/MemberListContainer/index.tsx
  apps/trainer/app/schedule-management/_components/MemberProfileCard/WorkoutSchedule.tsx
  apps/trainer/app/schedule-management/_components/MemberProfileCard/index.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationControlSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationNotAllowedCancelSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/index.tsx
  apps/trainer/app/schedule-management/_components/ScheduleBottomSheet.tsx
  apps/trainer/app/schedule-management/_components/TimeOption.tsx
  apps/trainer/app/schedule-management/_components/TimeOptionList.tsx
  apps/trainer/app/schedule-management/_constants/reservationConfig.ts
  apps/trainer/app/schedule-management/_libs/CalendarUtils.ts
  apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/DayoffAdderButton.tsx
  apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/index.tsx
  apps/trainer/app/schedule-management/dayoff-management/_components/Header.tsx
  apps/trainer/app/schedule-management/dayoff-management/page.tsx
  apps/trainer/app/schedule-management/fixed-reservation/_components/Header.tsx
  apps/trainer/app/schedule-management/fixed-reservation/_components/SelectTimeRouteButton.tsx
  apps/trainer/app/schedule-management/fixed-reservation/page.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/Header.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/FixedReservationAdderButton.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/indext.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_libs/getFixedReservationDatesAndTimes.ts
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/page.tsx
  apps/trainer/app/schedule-management/page.tsx
  apps/trainer/app/schedule-management/pending-reservations/_components/Header.tsx
  apps/trainer/app/schedule-management/pending-reservations/page.tsx
  apps/trainer/app/schedule-management/reservation/_components/Header.tsx
  apps/trainer/app/schedule-management/reservation/_components/ReservationAdderButton.tsx
  apps/trainer/app/schedule-management/reservation/_hooks/useFilteredMembers.tsx
  apps/trainer/app/schedule-management/reservation/page.tsx
  apps/trainer/components/BottomNavigation.tsx
  apps/trainer/components/Calendar/DaySchedule.tsx
  apps/trainer/components/Calendar/TimeBlock.tsx
  apps/trainer/components/Calendar/WeekSchedule.tsx
  apps/trainer/components/Calendar/index.tsx
  apps/trainer/components/ProfileCard.tsx
  apps/trainer/components/Providers/FooterProvider.tsx
  apps/trainer/components/TimeOptionList.tsx
  apps/trainer/constants/route.ts
  apps/trainer/services/types/reservations.dto.ts
  apps/trainer/services/types/userManagement.dto.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/InputWithIcon/index.tsx
  packages/ui/src/lib/DateController.ts
Labels: ✨feat

#129 [FLIZ-207/root] chore: husky, lint-staged 워크플로우 및 스크립트 작성
  .husky/pre-commit
  apps/trainer/app/schedule-management/pending-reservations/page.tsx
  commitlint.config.cjs
  package.json
Labels: 📎chore

#130 [FLIZ-211/user] feat: 유저 서비스 라우트 상수 정의
  apps/user/app/my-page/_components/LogoutButton.tsx
  apps/user/app/my-page/_components/PTInformation/ConnectedTrainerItem.tsx
  apps/user/app/my-page/_components/ProfileHeader.tsx
  apps/user/app/my-page/_constants/route.ts
  apps/user/app/my-page/my-information/_components/MemorizedChangePhoneLink.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
  apps/user/app/schedule-management/_components/ReservationAdder.tsx
  apps/user/app/schedule-management/_constants/route.ts
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
  apps/user/components/Providers/FooterProvider.tsx
  apps/user/constants/routes.ts
Labels: ✨feat

#131 [FLIZ-212/trainer] chore: 트레이너 도메인 RouteInstance 정의
  apps/trainer/app/schedule-management/_components/MemberProfileCard/index.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx
  apps/trainer/app/schedule-management/_components/TimeOptionList.tsx
  apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/DayoffAdderButton.tsx
  apps/trainer/app/schedule-management/fixed-reservation/_components/SelectTimeRouteButton.tsx
  apps/trainer/app/schedule-management/pending-reservations/page.tsx
  apps/trainer/app/sns-verification/_components/ResultStep.tsx
  apps/trainer/constants/route.ts
Labels: 📎chore

#128 [FLIZ-206/trainer] feat: 회원관리 + 회원 상세 정보 페이지 구현
  .husky/pre-commit
  apps/trainer/app/member-management/[memberId]/_components/Header.tsx
  apps/trainer/app/member-management/[memberId]/_components/MemberProfile.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryFilterButton.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/index.tsx
  apps/trainer/app/member-management/[memberId]/page.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/MemberProfileList.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtRemainingCountEditSheet.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtTotalCountEditSheet.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/SearchBar.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/index.tsx
  apps/trainer/app/member-management/_hooks/useFilteredMembers.tsx
  apps/trainer/app/member-management/page.tsx
  apps/trainer/components/ProfileCard.tsx
  apps/trainer/components/Providers/FooterProvider.tsx
  apps/trainer/constants/route.ts
  apps/trainer/hoc/WithBottomSheetStepper.tsx
  apps/trainer/hoc/__tests__/WithBottomSheetStepper.spec.tsx
  apps/trainer/tailwind.config.ts
  packages/core/.eslintrc.js
  packages/core/package.json
  packages/core/tsconfig.json
  packages/ui/src/components/PTHistoryItem.tsx
Labels: ✨feat

#132 [FLIZ-210/trainer] fix: 트레이너 도메인 빌드 에러 해결
  apps/trainer/app/schedule-management/reservation/page.tsx
Labels: 🐛fix

#133 [FLIZ-214/docs] fix: 스토리북 빌드 에러 해결
  docs/storybook/.eslintrc.js
  docs/storybook/package.json
  docs/storybook/stories/trainer/Calendar.stories.tsx
  docs/storybook/stories/trainer/ScheduleBottomSheet.stories.tsx
  docs/storybook/stories/trainer/TimeOption.stories.tsx
Labels: 🐛fix

#135 [FLIZ-221/trainer] feat: 트레이너 마이페이지 라우트 상수 변경
  apps/trainer/app/my-page/_components/LogoutButton.tsx
  apps/trainer/app/my-page/_components/MyPageHeader.tsx
  apps/trainer/app/my-page/_components/NavigateProfileItem.tsx
  apps/trainer/app/my-page/my-information/_components/MyInformationContainer.tsx
  apps/trainer/app/my-page/my-information/edit-verificated-phone/_components/PhoneVerificationContainer.tsx
  apps/trainer/app/my-page/my-information/edit-verificated-phone/page.tsx
  apps/trainer/app/my-page/page.tsx
  apps/trainer/constants/route.ts
Labels: ✨feat

#137 [FLIZ-223/trainer] feat: 트레이너 도메인 middleware를 통한 access/refresh 토큰 저장 방식 구현
  apps/trainer/app/apiCore.ts
  apps/trainer/middleware.ts
  apps/trainer/package.json
  apps/trainer/services/auth.ts
  apps/trainer/services/core.ts
  apps/trainer/services/myInformation.ts
  apps/trainer/services/reservations.ts
  apps/trainer/services/userManagement.ts
  packages/core/src/api/core.ts
  pnpm-lock.yaml
Labels: ✨feat

#139 [FILZ-226/user] feat: 유저 도메인 middleware를 통한 access/refresh 토큰 저장 방식 구현
  apps/user/app/apiCore.ts
  apps/user/middleware.ts
  apps/user/package.json
  apps/user/services/auth.ts
  apps/user/services/core.ts
  apps/user/services/myInformation.ts
  apps/user/services/notification.ts
  apps/user/services/reservations.ts
  pnpm-lock.yaml
Labels: ✨feat

#134 [FLIZ-215/trainer] feat: 트레이너 도메인의 예약 대기자를 확인하고 예약을 승인할 수 있는 페이지 구현
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationPendingSheet.tsx
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/ApproveButton.tsx
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/MemberCardList.tsx
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
  apps/trainer/app/schedule-management/pending-reservations/_utils/formatContinuousTimes.ts
  apps/trainer/app/schedule-management/pending-reservations/page.tsx
  apps/trainer/constants/Day.ts
  apps/trainer/services/types/reservations.dto.ts
  apps/trainer/services/types/userManagement.dto.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/FunnelSteps/WorkoutScheduleStep.tsx
  packages/ui/src/components/WorkoutForm.tsx
Labels: ✨feat

#138 [FLIZ-185/trainer] feat: 알림 페이지 UI 구현
  apps/trainer/app/notification/_components/NotificationItemContainer.tsx
  apps/trainer/app/notification/_components/NotificationSearch/MemberNotificationResult.tsx
  apps/trainer/app/notification/_components/NotificationSearch/index.tsx
  apps/trainer/app/notification/_components/SessionSetterSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/index.tsx
  apps/trainer/app/notification/_constants/titles.ts
  apps/trainer/app/notification/_utils/formatter.ts
  apps/trainer/app/notification/_utils/parser.ts
  apps/trainer/app/notification/connect/page.tsx
  apps/trainer/app/notification/disconnect/page.tsx
  apps/trainer/app/notification/page.tsx
  apps/trainer/app/notification/reservation-edit/page.tsx
  apps/trainer/app/notification/reservation/page.tsx
  apps/trainer/app/notification/session/page.tsx
  apps/trainer/queries/notification.ts
  apps/trainer/services/types/notification.dto.ts
  packages/core/src/api/types/common.ts
  packages/ui/src/components/NotificationItem/IconThumbnail.tsx
  packages/ui/src/components/NotificationItem/NotificationContent.tsx
  packages/ui/src/components/NotificationItem/NotificationItem.tsx
  packages/ui/src/components/NotificationItem/NotificationThumbnail.tsx
  packages/ui/src/components/NotificationItem/variants.ts
Labels: ✨feat
