Repository Fit-Links/FitLink-FE, pull requests merged in 2025-06, with the labels that each got.

#181 [FLIZ-305/user] fix: 로그인 링크 redirection 경로 버그 해결
  apps/trainer/constants/url.ts
  apps/user/app/login/_components/LoginButton/index.tsx
  apps/user/constants/url.ts
Labels: 🐛fix

#183 [FLIZ-308/trainer] feat: 고정 예약 시 요일, 및 시간을 트레이너가 PT 가능한 일정에 맞게 표기되도록 구현
  apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
  apps/trainer/app/schedule-management/_components/Calendar/WeekRow.tsx
  apps/trainer/app/schedule-management/fixed-reservation/_components/SelectTimeRouteButton.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/indext.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/page.tsx
  packages/ui/src/components/DayOfWeekPicker/Context.tsx
  packages/ui/src/components/DayOfWeekPicker/context.tsx
  packages/ui/src/components/DayOfWeekPicker/index.tsx
  packages/ui/src/hooks/useDayOfWeekPickerContext.ts
Labels: ✨feat

#184 [FLIZ-309/trainer] feat: 트레이너 도메인 최상단에서 mutation 성공/실패 메시지 띄우는 기능 구현(react-toastify)
  apps/trainer/app/schedule-management/reservation/_components/ReservationAdderButton.tsx
  apps/trainer/components/Providers/index.tsx
  apps/trainer/package.json
  pnpm-lock.yaml
Labels: ✨feat

#186 [FLIZ-311/trainer] fix: 트레이너 도메인 예약 불가 설정 바텀시트 버그 해결
  apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx
  apps/trainer/app/schedule-management/_components/TimeOptionList.tsx
Labels: 🐛fix

#190 [FLIZ-318/user] refactor: 유저 도메인 mutation 요청 고도화 및 사용성 개선
  apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
  apps/user/app/schedule-management/_components/Calendar/index.tsx
  apps/user/app/schedule-management/_hooks/mutation/useReservationCancelMutation.ts
  apps/user/app/schedule-management/_libs/checkReservationIsFuture.ts
  apps/user/app/schedule-management/_utils/reservationMerger.ts
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
  apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationChangeMutation.ts
  apps/user/app/schedule-management/reservation/[mode]/page.tsx
Labels: 🛠️refactor

#193 [FLIZ-320/trainer] feat: notification 도메인 mutation 성공 후 쿼리 invalidation 추가
  apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
  apps/trainer/app/notification/page.tsx
Labels: ✨feat

#192 [FLIZ-317/user] feat: FCM 로직 구현
  apps/user/app/register/_components/ResultStep.tsx
  apps/user/app/register/_hooks/useFCMToken.ts
  apps/user/app/register/_hooks/useRegisterFcmToken.ts
  apps/user/app/test/page.tsx
  apps/user/components/Splash.tsx
  apps/user/constants/firebase.ts
  apps/user/public/firebase-messaging-sw.js
  apps/user/utils/fcm.ts
Labels: ✨feat

#194 [FLIZ-301/root] fix: register 단계에서 userProfileImage 등록 API 오류 해결
  apps/trainer/app/register/_components/RegisterFunnel.tsx
  apps/user/app/register/_components/RegisterFunnel.tsx
Labels: 🐛fix

#196 [FLIZ-315] feat: 통합 ErrorBoundary 구현 및 마이페이지 PT히스토리 무한 스크롤
  apps/trainer/app/error.tsx
  apps/trainer/app/global-error.tsx
  apps/trainer/app/my-page/_components/MyPageContainer.tsx
  apps/trainer/app/my-page/_components/ProfileItemForRouting.tsx
  apps/trainer/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/trainer/app/my-page/my-information/_components/MyInformationContainer.tsx
  apps/trainer/app/my-page/my-information/_components/Skeleton/index.tsx
  apps/trainer/app/my-page/my-information/page.tsx
  apps/trainer/app/my-page/page.tsx
  apps/trainer/components/QueryErrorFallback/ErrorFallback.tsx
  apps/trainer/components/QueryErrorFallback/index.tsx
  apps/user/app/error.tsx
  apps/user/app/global-error.tsx
  apps/user/app/my-page/_components/MyPageContainer.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryCotainer.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/EditPreferenceTimeContainer.tsx
  apps/user/app/my-page/my-information/_components/BottomSheet/EditProfileBottomSheet.tsx
  apps/user/app/my-page/my-information/page.tsx
  apps/user/app/my-page/my-trainer-information/page.tsx
  apps/user/app/my-page/page.tsx
  apps/user/components/Providers/FooterProvider.tsx
  apps/user/components/QueryErrorFallback/ErrorFallback.tsx
  apps/user/components/QueryErrorFallback/index.tsx
  packages/ui/src/components/GlobalFallback.tsx
  packages/ui/src/components/PTHistoryItem.tsx
Labels: ✨feat

#198 [FLIZ-324] feat: 외부 도메인 이미지 가져오기 최적화
  apps/user/next.config.mjs
Labels: ✨feat

#200 [FLIZ-325/trainer] fix: 예약 데이터가 2개 이상일 경우 서로 다른 데이터로 취급하여 예약 데이터를 나타내도록 유틸 함수 수정
  apps/trainer/app/schedule-management/_utils/reservationMerger.ts
Labels: 🐛fix

#204 [FLIZ-331/trainer] fix: 알림 종류별 subpage에 footer 없는 버그 fix
  apps/trainer/components/BottomNavigation.tsx
  apps/trainer/components/Providers/FooterProvider.tsx
Labels: 🐛fix

#207 [FLIZ-329/user] feat: 트레이너 캘린더/예약 페이지 Loading Fallback UI 적용
  apps/trainer/app/schedule-management/page.tsx
  apps/trainer/components/Fallback/LoadingFallback.tsx
  apps/user/app/layout.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
  apps/user/app/schedule-management/_components/Calendar/index.tsx
  apps/user/app/schedule-management/_components/Fallback/ConnectionFallback.tsx
  apps/user/app/schedule-management/page.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/Fallback/PtTimeSelectorFallback.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/ReservationRequestor.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx
  apps/user/components/Fallback/LoadingFallback.tsx
  apps/user/components/Providers/FooterProvider.tsx
  packages/config-tailwind/.eslintrc.js
  packages/config-tailwind/tailwind.config.ts
  packages/ui/src/components/PhoneVerification/index.tsx
Labels: ✨feat

#208 [FLIZ-334] feat: 마이페이지 useMutation() 훅으로 처리 및
  apps/trainer/app/my-page/_components/MyPagePending.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleApplyAtStep/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_hooks/useAddScheduleMutation.ts
  apps/trainer/app/my-page/edit-workout-schedule/_hooks/useDeleteScheduleMutation.ts
  apps/user/app/my-page/_components/MyPagePending.tsx
  apps/user/app/my-page/connect-trainer/_components/InputOTP/index.tsx
  apps/user/app/my-page/connect-trainer/_hooks/useRequestConnectTrainer.ts
  apps/user/app/my-page/edit-workout-schedules/_components/EditPreferenceTimeContainer.tsx
  apps/user/app/my-page/edit-workout-schedules/_hooks/useEditPreferenceTimeMutation.ts
  apps/user/app/my-page/my-trainer-information/_components/TrainerUnlinkItem.tsx
  apps/user/app/my-page/my-trainer-information/_hooks/useUnlinkTrainerMutation.ts
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
  packages/ui/src/components/InputOTP.tsx
Labels: ✨feat

#211 [FLIZ-341/trainer] fix: 예약 취소 거절 후, 캘린더 페이지에 들어가니, TypeError가 나타나며 캘린더 페이지가 죽는 이슈 해결
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/index.tsx
  apps/trainer/app/schedule-management/_constants/reservationConfig.ts
  packages/core/src/api/types/common.ts
Labels: 🐛fix

#212 [FLIZ-343/trainer] fix: 트레이너 도메인 고정 예약 validation 함수 수정 및 , 회원/트레이너 도메인에서 사용되지 않는 UI 제거
  apps/trainer/app/member-management/[memberId]/_components/MemberProfile.tsx
  apps/trainer/app/schedule-management/_components/Fallback/FixedReservationListFallback.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_components/SelectPtTimesContainer/FixedReservationAdderButton.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_utils/fixReservationUtils.ts
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
  apps/trainer/app/schedule-management/pending-reservations/page.tsx
  apps/user/app/schedule-management/_components/Calendar/Header.tsx
  apps/user/app/schedule-management/reservation/[mode]/_hooks/mutation/useReservationChangeMutation.ts
Labels: 🐛fix

#213 [FLIZ-344/trainer] fix: 예약 대기 상세 조회에서 발생하는 서버와 클라이언트의 시간차 에러 수정
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
  apps/trainer/package.json
  pnpm-lock.yaml
Labels: 🐛fix

#214 [FLIZ-345/trainer] fix: 예약 대기 상세 조회 시간차 오류 재수정
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
Labels: 🐛fix

#215 [FLIZ-340] feat: 트레이너 마이페이지 변경 예정시간 제거 기능 구현
  apps/trainer/app/my-page/_components/DeleteScheduleBottomSheet.tsx
  apps/trainer/app/my-page/_components/EditScheduleBottomSheet.tsx
  apps/trainer/app/my-page/_components/MyDayOffContainer.tsx
  apps/trainer/app/my-page/_components/ScheduleInformation.tsx
  apps/trainer/app/my-page/_components/Skeleton/MyPTHistorySkeleton.tsx
  apps/trainer/app/my-page/_components/Skeleton/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleApplyAtStep/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
  apps/trainer/app/my-page/page.tsx
  apps/trainer/components/PTSchedule.tsx
Labels: ✨feat

#216 [FLIZ-347] fix: InputOTP 키보드 타입 변경
  apps/trainer/app/error.tsx
  apps/user/app/error.tsx
  apps/user/app/my-page/_components/PTHistory/PTHistoryContent.tsx
  packages/ui/src/components/InputOTP.tsx
Labels: 🐛fix

#223 FLIZ-359 fix: 예약 대기 API 상세 조회 시간 + 9
  apps/trainer/app/schedule-management/pending-reservations/_components/PendingReservationContainer/index.tsx
Labels: 🐛fix

#224 [FLIZ-362/trainer] fix: 회원 연동 해제, 예약 변경 요청 승인 API EndPoint 수정
  apps/trainer/services/reservations.ts
  apps/trainer/services/types/userManagement.dto.ts
  apps/trainer/services/userManagement.ts
Labels: 🐛fix

#226 [FLIZ-372/trainer] refactor: 캘린더 타임블록 UI 변경 수정, 예약 현황 데이터에서 최근 데이터가 과거 데이터를 OverWrite 할 수 있도록 컨버팅 함수 수정
  apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
  apps/trainer/app/schedule-management/_utils/reservationMerger.ts
Labels: 🛠️refactor

#227 [FLIZ-370/root] feat: 마이페이지에 푸시 알림 허용 스위치 추가
  apps/trainer/app/my-page/my-information/_components/MyInformationContainer.tsx
  apps/trainer/types/navigator.d.ts
  apps/user/app/my-page/my-information/_components/MyDetailInformations.tsx
  apps/user/types/navigator.d.ts
  packages/ui/src/components/ProfileItem.tsx
  packages/ui/src/components/PushPermissionSwitch.tsx
  packages/ui/src/types/navigator.d.ts
  packages/ui/src/utils/getEnvironment.ts
Labels: ✨feat

#229 [FLIZ-346/trainer] fix: 예약 변경 승인 API 요청 형식 fix
  packages/ui/src/lib/DateController.ts
Labels: 🐛fix

#230 [FLIZ-377/trainer] feat: 트레이너 도메인 고정 예약 변경 기능 구현
  apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
  apps/trainer/app/schedule-management/_components/Calendar/index.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationControlSheet.tsx
  apps/trainer/app/schedule-management/fixed-reservation/select-pt-times/_hooks/mutations/useFixReservationChangeMutation.ts
  apps/trainer/app/schedule-management/page.tsx
Labels: ✨feat

#233 [FLIZ-379/root] feat: 트레이너 도메인 무한 스크롤 기능 구현
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/index.tsx
  apps/trainer/app/schedule-management/_components/MemberListContainer/MemberCardList.tsx
  apps/trainer/app/schedule-management/_components/MemberListContainer/index.tsx
  apps/trainer/hooks/useIntersectionObserver.ts
  apps/trainer/queries/userManagement.ts
Labels: ✨feat

#235 [FLIZ-381/style] style: PWA 배경색상 bg-background-primary 색상으로 변경
  apps/trainer/public/manifest.json
  apps/user/public/manifest.json
Labels: 💄style

#237 [FLIZ-373/user] feat: 유저 도메인 캘린더에서 선택한 날짜가 예약 페이지로 그대로 전달되는 기능 추가
  apps/user/app/schedule-management/_components/Calendar/index.tsx
  apps/user/app/schedule-management/_components/ReservationAdder.tsx
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/index.tsx
  apps/user/constants/routes.ts
Labels: ✨feat

#238 [FLIZ-380/trainer] feat: 회원가입/수업 시간 설정 단계에서 휴무일 여부 기본값을 true로 수정
  apps/trainer/components/FunnelSteps/TrainerScheduleStep.tsx
Labels: ✨feat

#240 [FLIZ-385/ui] fix: 모바일 화면에서 hover 이펙트 제거
  apps/trainer/app/login/_components/LoginButton/index.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryFilterButton.tsx
  apps/trainer/app/member-management/[memberId]/_components/PtHistoryContainer/PtHistoryList.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/MemberProfileList.tsx
  apps/trainer/app/my-page/my-information/_components/BottomSheet/SheetItem.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationChangeSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
  apps/trainer/app/schedule-management/_components/Calendar/TimeBlock.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationControlSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationNotAllowedCancelSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx
  apps/trainer/app/schedule-management/_components/TimeOption.tsx
  apps/trainer/app/schedule-management/_constants/reservationConfig.ts
  apps/trainer/components/BottomNavigation.tsx
  apps/trainer/components/ProfileCard.tsx
  apps/user/app/login/_components/LoginButton/index.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationCancelSheet.tsx
  apps/user/app/schedule-management/_components/BottomSheet/ReservationStatusSheet.tsx
  apps/user/app/schedule-management/_components/Calendar/WeekRow.tsx
  apps/user/components/BottomNavigation.tsx
  apps/user/components/SheetItem.tsx
  packages/ui/src/components/Accordion/index.tsx
  packages/ui/src/components/Button.tsx
  packages/ui/src/components/ChevronTrigger.tsx
  packages/ui/src/components/DayOfTwoWeekPicker.tsx
  packages/ui/src/components/DayOfWeekPicker/index.tsx
  packages/ui/src/components/DayPicker/index.tsx
  packages/ui/src/components/PTHistoryItem.tsx
  packages/ui/src/components/TimeCellToggleGroup.tsx
  packages/ui/src/components/ToggleGroup.tsx
Labels: 🐛fix

#239 [FLIZ-368/ui] fix: 안드로이드 환경에서 휴대폰 인증 메시지 전송 지원
  apps/trainer/app/notification/_components/SessionSetterSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ConnectTrainerSheet.tsx
  apps/trainer/components/MutationStatusSheet.tsx
  packages/ui/src/components/PhoneVerification/PhoneVerificationGuide.tsx
  packages/ui/src/components/PhoneVerification/PhoneVerificationImage.tsx
  packages/ui/src/components/PhoneVerification/PhoneVerificationNotice.tsx
  packages/ui/src/components/PhoneVerification/VerificationInfoDialog.tsx
  packages/ui/src/components/PhoneVerification/index.tsx
  packages/ui/src/utils/copyToClipboard.ts
Labels: 🐛fix

#241 [FLIZ-391/ui] fix: 안드로이드 환경 PhoneVerification 버그 fix
  packages/ui/src/components/PhoneVerification/index.tsx
Labels: 🐛fix

#243 [FLIZ-394/trainer] feat: 트레이너가 직접 예약시 같은 날짜에 같은 회원이 두 번 이상 수업 예약이 진행될 수 없다는 정책 반영
  apps/trainer/app/schedule-management/reservation/_components/ReservationAdderButton.tsx
  apps/trainer/app/schedule-management/reservation/page.tsx
  apps/trainer/components/Providers/index.tsx
  apps/user/components/Providers/index.tsx
Labels: ✨feat

#244 [FLIZ-389/root] fix: 알림 item bug fix
  apps/trainer/app/notification/_components/NotificationItemContainer.tsx
  apps/trainer/app/notification/_components/NotificationItemFallback.tsx
  apps/trainer/app/notification/_components/NotificationSearch/MemberNotificationResult.tsx
  apps/trainer/app/notification/_components/SheetRenderer/ReservationCancelSheet.tsx
  apps/trainer/app/notification/_components/SheetRenderer/index.tsx
  apps/trainer/app/notification/_utils/notificationParser.ts
  apps/trainer/app/notification/_utils/parseKoreanDateString.ts
  apps/trainer/app/notification/_utils/parser.ts
  apps/trainer/app/notification/page.tsx
  apps/trainer/app/notification/reservation-cancel/page.tsx
  apps/trainer/app/notification/reservation-change/page.tsx
  apps/trainer/app/notification/session/page.tsx
  apps/user/app/notification/_components/NotificationContainer.tsx
  apps/user/app/notification/_components/NotificationItemContainer.tsx
  apps/user/app/notification/_utils/notificationParser.ts
  packages/ui/src/components/NotificationItem/IconThumbnail.tsx
  packages/ui/src/components/NotificationItem/NotificationContent.tsx
  packages/ui/src/components/NotificationItem/NotificationItem.tsx
Labels: 🐛fix

#248 [FLIZ-388/trainer] feat: FCM foreground 로직 추가
  apps/trainer/app/notification/_components/NotificationContainer.tsx
  apps/trainer/app/notification/_components/NotificationItemContainer.tsx
  apps/trainer/app/notification/_components/NotificationProvider.tsx
  apps/trainer/app/notification/_components/NotificationSearch/MemberNotificationResult.tsx
  apps/trainer/app/notification/_utils/notificationParser.ts
  apps/trainer/app/notification/_utils/parseKoreanDateString.ts
  apps/trainer/app/notification/connect/_constants/index.ts
  apps/trainer/app/notification/connect/page.tsx
  apps/trainer/app/notification/disconnect/_constants/index.ts
  apps/trainer/app/notification/disconnect/page.tsx
  apps/trainer/app/notification/layout.tsx
  apps/trainer/app/notification/page.tsx
  apps/trainer/app/notification/reservation-cancel/_constants/index.ts
  apps/trainer/app/notification/reservation-cancel/page.tsx
  apps/trainer/app/notification/reservation-change/_constants/index.ts
  apps/trainer/app/notification/reservation-change/page.tsx
  apps/trainer/app/notification/reservation/_constants/index.ts
  apps/trainer/app/notification/reservation/page.tsx
  apps/trainer/app/notification/session/_constants/index.ts
  apps/trainer/app/notification/session/page.tsx
  apps/trainer/app/register/_hooks/useRegisterFcmToken.ts
  apps/trainer/app/test/page.tsx
  apps/trainer/components/BottomNavigation.tsx
  apps/trainer/components/NotificationBell.tsx
  apps/trainer/components/Providers/index.tsx
  apps/trainer/components/Splash.tsx
  apps/trainer/hooks/useFcmListener.ts
  apps/trainer/lib/firebase.ts
  apps/trainer/lib/firebaseMessaging.ts
  apps/trainer/lib/toastService.tsx
  apps/trainer/queries/notification.ts
  apps/trainer/store/notificationStore.ts
  apps/trainer/utils/fcm.ts
  packages/ui/src/components/Header.tsx
Labels: ✨feat

#250 [FLIZ-399/root] feat: 푸시 알림 스위치에 FCM 연동 로직 추가
  apps/trainer/app/my-page/my-information/_components/MyInformationContainer.tsx
  apps/trainer/app/register/_hooks/useRegisterFcmToken.ts
  apps/user/app/my-page/my-information/_components/MyDetailInformations.tsx
  apps/user/app/register/_hooks/useRegisterFcmToken.ts
  packages/ui/src/components/Button.tsx
  packages/ui/src/components/PushPermissionSwitch.tsx
  packages/ui/src/hooks/usePushPermissionSwitch.ts
Labels: ✨feat

#251 [FLIZ-338/root] chore: favicon.ico 추가
  apps/trainer/app/icon.ico
  apps/user/app/icon.ico
Labels: 📎chore
