Repository Fit-Links/FitLink-FE, pull requests merged in 2025-08, with the labels that each got.

#293 [FLIZ-453/root] refactor: 페이지 router 특징에 따른 라우팅 함수 (push, replace) 적용
  apps/trainer/app/my-page/_components/LogoutButton.tsx
  apps/trainer/app/my-page/_components/MyPageHeader.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/ScheduleChangeResultSheet.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleConfirmStep/index.tsx
  apps/trainer/app/my-page/edit-workout-schedule/_components/EditScheduleFunnel.tsx
  apps/trainer/app/schedule-management/dayoff-management/_components/DayoffCalendarContainer/DayoffAdderButton.tsx
  apps/user/app/my-page/_components/LogoutButton.tsx
  apps/user/app/my-page/_components/ProfileHeader.tsx
  apps/user/app/my-page/connect-trainer/_components/InputOTP/index.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/BottomSheet/SuccessEditPreferenceTimeBottomSheet.tsx
  packages/core/src/api/core.ts
Labels: 🛠️refactor

#296 [FLIZ-458/root] feat: root loading.tsx 추가
  apps/trainer/app/loading.tsx
  apps/user/app/loading.tsx
Labels: ✨feat

#302 [FLIZ-462] feat: axios 토큰 검사 시, SSR에서의 window 참조 방지를 위한 조건 설정
  packages/core/src/api/core.ts
Labels: ✨feat

#298 [FLIZ-461/root] feat: 로고 우측에 사용자 가이드 페이지 링크 연결
  packages/ui/src/components/Header.tsx
Labels: ✨feat

#307 [FLIZ-466/root] fix: 3차 QA 적용
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtCountEditSheet.tsx
  apps/trainer/components/UserPermissionGuard.tsx
  apps/user/app/schedule-management/_utils/timeCellGenerator.ts
  apps/user/app/schedule-management/reservation/[mode]/_components/ReservationContainer/PtTimeSelector/index.tsx
  apps/user/components/UserPermissionGuard.tsx
Labels: 🐛fix

#308 [FLIZ-467/root] chore: prod 배포 version 관리 CI/CD 구축
  .changeset/README.md
  .changeset/config.json
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
  release-dev.sh
Labels: 📎chore

#309 [FLIZ-468/root] chore: vercel prod 배포 CI/CD 구축
  .github/workflows/deploy_prod.yml
Labels: 📎chore

#312 [FLIZ-470/root] fix: deploy_prod 워크플로우 bug fix
  .github/workflows/deploy_prod.yml
Labels: 🐛fix
