Repository Fit-Links/FitLink-FE, pull requests merged in 2025-07, with the labels that each got.

#256 [FLIZ-404/user] fix: 알림 페이지 Header SSR bugfix
  apps/user/app/notification/layout.tsx
  apps/user/app/notification/page.tsx
Labels: 🐛fix

#258 [FLIZ-401/root] feat: 알림 읽기 API 연결
  apps/trainer/app/notification/page.tsx
  apps/trainer/services/notification.ts
  apps/user/app/notification/_components/NotificationContainer.tsx
  apps/user/services/notification.ts
Labels: ✨feat

#264 [FLIZ-415/trainer] style: 트레이너 도메인 캘린더 시간 컬럼 UI 깨짐 해결
  apps/trainer/app/schedule-management/_components/Calendar/TimeColumn.tsx
  apps/trainer/app/schedule-management/_components/Calendar/index.tsx
Labels: 💄style

#263 [FLIZ-413/root] feat: BottomNavigation 클릭 시, 즉시 반응하도록 구현
  apps/trainer/components/BottomNavigation.tsx
  apps/trainer/components/Providers/FooterProvider.tsx
  apps/user/components/BottomNavigation.tsx
  apps/user/components/Providers/FooterProvider.tsx
Labels: ✨feat

#266 [FLIZ-416/trainer] fix: 예약 페이지 사파리 date 생성자 이슈 해결
  apps/trainer/app/schedule-management/_components/TimeOptionList.tsx
  apps/trainer/app/schedule-management/reservation/_components/ReservationAdderButton.tsx
  apps/trainer/app/schedule-management/reservation/page.tsx
Labels: 🐛fix

#267 [FLIZ-407/user] style: 레이아웃 통일
  apps/user/app/layout.tsx
  apps/user/app/login/page.tsx
  apps/user/app/my-page/connect-trainer/_components/ConnectTrainerContainer.tsx
  apps/user/app/my-page/connect-trainer/page.tsx
  apps/user/app/my-page/edit-workout-schedules/_components/EditPreferenceTimeContainer.tsx
  apps/user/app/my-page/edit-workout-schedules/page.tsx
  apps/user/app/my-page/my-information/page.tsx
  apps/user/app/my-page/my-information/verify-phone/page.tsx
  apps/user/app/my-page/my-trainer-information/_components/MyTrainerInformationContainer.tsx
  apps/user/app/my-page/my-trainer-information/page.tsx
  apps/user/app/my-page/page.tsx
  apps/user/app/notification/_components/NotificationContainer.tsx
  apps/user/app/notification/page.tsx
  apps/user/app/schedule-management/page.tsx
  apps/user/components/Logo.tsx
  apps/user/components/Providers/FooterProvider.tsx
  apps/user/components/Providers/HeaderProvider.tsx
  apps/user/constants/styles.ts
  apps/user/public/logo_colored.png
Labels: 💄style

#270 [FLIZ-426/root] fix: FCM 데이터 파싱 로직 수정
  apps/trainer/hooks/useFcmListener.ts
  apps/trainer/public/firebase-messaging-sw.js
  apps/user/hooks/useFcmListener.ts
  apps/user/public/firebase-messaging-sw.js
Labels: 🐛fix

#273 [FLIZ-432/trainer] fix: 알림 종류 정책 업데이트 및 리팩토링
  apps/trainer/app/notification/_components/NotificationAccordion.tsx
  apps/trainer/app/notification/_components/NotificationContainer.tsx
  apps/trainer/app/notification/_components/NotificationSearch/MemberNotificationResult.tsx
  apps/trainer/app/notification/_components/NotificationSideBar.tsx
  apps/trainer/app/notification/_constants/index.ts
  apps/trainer/app/notification/_constants/titles.ts
  apps/trainer/app/notification/connect/_constants/index.ts
  apps/trainer/app/notification/connect/page.tsx
  apps/trainer/app/notification/disconnect/_constants/index.ts
  apps/trainer/app/notification/disconnect/page.tsx
  apps/trainer/app/notification/reservation-cancel/_constants/index.ts
  apps/trainer/app/notification/reservation-cancel/page.tsx
  apps/trainer/app/notification/reservation-change/_constants/index.ts
  apps/trainer/app/notification/reservation-change/page.tsx
  apps/trainer/app/notification/reservation/_constants/index.ts
  apps/trainer/app/notification/reservation/page.tsx
  apps/trainer/app/notification/session/_constants/index.ts
  apps/trainer/app/notification/session/page.tsx
Labels: 🐛fix, 🛠️refactor

#276 [FLIZ-437/user] feat: 트레이너 연동상태 표시에 트레이너 이름 추가
  apps/user/app/my-page/_components/PTInformation/ConnectedTrainerItem.tsx
Labels: ✨feat

#279 [FLIZ-439/root] style: flex-1 값을 통하여 버튼 제외한 인증 안내 영역 전체 페이지 사이즈 할당
  apps/trainer/components/Providers/index.tsx
  apps/user/components/Providers/index.tsx
  packages/ui/src/components/PhoneVerification/index.tsx
Labels: 💄style

#280 [FLIZ-425/root] feat: 회원가입 문자 인증 단계에서 문자 전송 시 interval 로직 추가
  apps/trainer/app/sns-verification/page.tsx
  apps/user/app/sns-verification/page.tsx
  packages/ui/src/components/PhoneVerification/index.tsx
Labels: ✨feat

#285 [FLIZ-445/root] fix: 양 도메인 Role 체크 후 잘못된 경로 check 로직 수정
  apps/trainer/middleware/handlers/handleRedirectByUserRole.ts
  apps/user/middleware/handlers/handleRedirectByUserRole.ts
Labels: 🐛fix

#286 FLIZ-446 refactor: 유저 롤 체크 로직 이동
  apps/trainer/middleware.ts
  apps/trainer/middleware/handlers/handleTokenFromUrl.ts
  apps/user/middleware.ts
  apps/user/middleware/handlers/handleTokenFromUrl.ts
Labels: 🛠️refactor

#287 [FLIZ-447/root] fix: HOTFIX
  apps/trainer/app/my-page/my-information/page.tsx
  apps/trainer/app/notification/_components/SheetRenderer/SessionCompleteSheet.tsx
  packages/ui/src/components/ProfileItem.tsx
Labels: 🐛fix

#288 [FLIZ-449/root] feat: background 푸시알림 클릭핸들러 추가
  apps/trainer/public/firebase-messaging-sw.js
  apps/user/public/firebase-messaging-sw.js
Labels: ✨feat

#289 [FLIZ-450/ui] fix: subHeader sticky position 유지를 위해 레이아웃 수정
  packages/ui/src/components/Header.tsx
Labels: 🐛fix

#290 [FLIZ-429/trainer] feat: 잔여/총 PT 세션 통합 수정 바텀 시트 구현 + 홍길동 더미데이터 제거 + 회원 도메인 버그 Fix
  apps/trainer/app/member-management/_components/MemberManagementContainer/MemberProfileList.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/PtCountEditSheet.tsx
  apps/trainer/app/member-management/_components/MemberManagementContainer/index.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationControlSheet.tsx
  apps/trainer/app/schedule-management/_components/ReservationManagementSheet/ReservationOutcomeSheet.tsx
  apps/user/app/schedule-management/_utils/reservationMerger.ts
Labels: ✨feat
