Repository Fit-Links/FitLink-FE, pull requests merged in 2025-01, with the labels that each got.

#28 [PRIZ-31/root] chore: JIRA 연동 설정
  .husky/prepare-commit-msg
  commitlint.config.cjs
Labels: 📎chore

#29 [PRIZ-30/ui] chore: jest 및 testing-library/react 환경 구축
  packages/config-eslint/react-internal.js
  packages/ui/jest.config.js
  packages/ui/jest.setup.ts
  packages/ui/package.json
  packages/ui/src/lib/test/test-utils.tsx
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: 📎chore

#33 [PRIZ-43/root] chore: @5unwan/storybook 관련 turbo script 추가
  package.json
Labels: 📎chore

#34 [PRIZ-39/ui] feat: Dialog 컴포넌트 구현
  docs/storybook/stories/Dialog.stories.tsx
  packages/config-tailwind/package.json
  packages/config-tailwind/tailwind.config.ts
  packages/ui/package.json
  packages/ui/src/components/Dialog.tsx
  pnpm-lock.yaml
Labels: ✨feat

#30 [#27/ui] feat: Avatar 공통 컴포넌트 구현
  docs/storybook/stories/Avatar.stories.tsx
  docs/storybook/stories/FontSize.mdx
  packages/config-tailwind/tailwind.config.ts
  packages/ui/package.json
  packages/ui/src/components/Avatar.tsx
  pnpm-lock.yaml
Labels: ✨feat

#31 [PRIZ 34/ui] feat: Stepper 공통 컴포넌트 구현
  docs/storybook/stories/Stepper.stories.tsx
  packages/ui/src/components/Stepper.tsx
  packages/ui/src/components/__tests__/Stepper.spec.tsx
  packages/ui/src/hooks/__tests__/useCallbackRef.spec.tsx
  packages/ui/src/hooks/__tests__/useControllableState.spec.tsx
  packages/ui/src/hooks/useCallbackRef.tsx
  packages/ui/src/hooks/useControllableState.tsx
Labels: ✨feat

#37 [FLIZ-5/root] chore: pnpm 버전 업데이트
  package.json
Labels: 📎chore

#36 [PRIZ-41/ui] feat: Switch 컴포넌트 구현
  docs/storybook/package.json
  docs/storybook/stories/Switch.stories.tsx
  docs/storybook/tsconfig.json
  packages/ui/package.json
  packages/ui/src/components/Switch.tsx
  pnpm-lock.yaml
Labels: ✨feat

#55 [FLIZ-27/root] fix: pnpm-lock 버전 오류 hotfix
  pnpm-lock.yaml
Labels: 🐛fix

#32 [PRIZ-32/ui] feat: Sheet 컴포넌트 구현
  docs/storybook/stories/Sheet.stories.tsx
  packages/ui/src/components/Sheet.tsx
  pnpm-lock.yaml
Labels: ✨feat

#39 [FLIZ-11/ui] feat: ToggleGroup 컴포넌트 구현
  docs/storybook/package.json
  docs/storybook/stories/ToggleGroup.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/ToggleGroup.tsx
  pnpm-lock.yaml
Labels: ✨feat

#48 [FLIZ-23/ui] feat: Carousel 컴포넌트 구현
  docs/storybook/stories/Carousel.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/Carousel.tsx
  pnpm-lock.yaml
Labels: ✨feat

#47 [FLIZ-14/ui] feat: NotificationItem 구현
  docs/storybook/stories/NotificationItem.stories.tsx
  packages/ui/src/components/NotificationItem/IconThumbnail.tsx
  packages/ui/src/components/NotificationItem/NotificationContent.tsx
  packages/ui/src/components/NotificationItem/NotificationItem.tsx
  packages/ui/src/components/NotificationItem/NotificationThumbnail.tsx
  packages/ui/src/components/NotificationItem/variants.ts
  packages/ui/src/lib/DateController.ts
  pnpm-lock.yaml
Labels: ✨feat

#42 [FILZ-17/ui] feat: Accordion 공통 컴포넌트 구현
  docs/storybook/package.json
  docs/storybook/stories/Accordion.stories.tsx
  packages/config-tailwind/tailwind.config.ts
  packages/ui/package.json
  packages/ui/src/components/Accordion/context.tsx
  packages/ui/src/components/Accordion/index.tsx
  packages/ui/src/hooks/useAccordionContext.ts
  pnpm-lock.yaml
Labels: ✨feat

#41 [FILZ-7/ui] feat: Dropdown 공통 컴포넌트 구현
  docs/storybook/stories/Dropdown.stories.tsx
  packages/ui/jest.config.js
  packages/ui/src/components/Dropdown/context.tsx
  packages/ui/src/components/Dropdown/index.tsx
  packages/ui/src/components/__tests__/Dropdown.spec.tsx
  packages/ui/src/hooks/useDropdownContext.ts
  pnpm-lock.yaml
Labels: ✨feat

#52 [FLIZ-24/ui] feat: Button 컴포넌트 구현
  docs/storybook/stories/Button.stories.tsx
  docs/storybook/stories/DayofWeekPicker.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/Button.tsx
  packages/ui/src/components/DayOfWeekPicker/index.tsx
  packages/ui/src/hooks/useDayOfWeekPickerContext.ts
  pnpm-lock.yaml
Labels: ✨feat

#45 [FLIZ-18/ui] feat: TimePicker 공통 컴포넌트 구현
  docs/storybook/stories/TimePicker.stories.tsx
  packages/config-tailwind/tailwind.config.ts
  packages/config-tailwind/variables.css
  packages/ui/package.json
  packages/ui/src/components/TimePicker.tsx
  pnpm-lock.yaml
Labels: ✨feat

#54 [FLIZ-25/ui] feat: Input를 확장한 공통 컴포넌트(InputWithIcon, InputWithLabel) 구현
  docs/storybook/stories/InputWithIcon.stories.tsx
  docs/storybook/stories/InputWithLabel.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/InputWithIcon/context.tsx
  packages/ui/src/components/InputWithIcon/index.tsx
  packages/ui/src/components/InputWithLabel/context.tsx
  packages/ui/src/components/InputWithLabel/index.tsx
  packages/ui/src/components/Label.tsx
  packages/ui/src/hooks/useInputWithIconContext.ts
  packages/ui/src/hooks/useInputWithLabelContext.ts
  pnpm-lock.yaml
Labels: ✨feat

#35 [PRIZ 36/ui] feat. Text 공통 컴포넌트 구현
  docs/storybook/stories/Text.stories.tsx
  packages/ui/src/components/Text.tsx
Labels: ✨feat

#56 [FLIZ-32/ui] fix: DayOfWeekPickerContext import 오류 해결
  packages/ui/src/components/DayOfWeekPicker/context.tsx
Labels: 🐛fix

#46 [FLIZ-21/ui] Spinner 공통 컴포넌트 구현
  docs/storybook/stories/Spinner.stories.tsx
  packages/ui/src/components/Spinner.tsx
Labels: ✨feat

#58 [FLIZ-30/root] chore: 개인 vercel 자동 배포 설정
  .github/workflows/deploy.yml
  build.sh
Labels: 📎chore

#59 [FLIZ-41/root] fix: build.sh 오류 해결
  build.sh
Labels: 🐛fix

#60 [FLIZ-42/root] fix: build.sh 스크립트 수정
  build.sh
Labels: 🐛fix

#61 [FLIZ-45/root] docs: README.md 초안 작성
  README.md
  apps/trainer/README.md
  apps/user/README.md
  docs/storybook/README.md
  packages/ui/README.md
Labels: 📝docs

#44 [FLIZ-19/ui] feat: Drawer 공통 컴포넌트 구현
  docs/storybook/stories/Drawer.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/Drawer.tsx
Labels: ✨feat
