Repository Fit-Links/FitLink-FE, pull requests merged in 2025-02, with the labels that each got.

#64 [FLIZ-57/ui] fix: Dropdown 컴포넌트 바깥쪽 클릭시 닫히지 않는 버그 수정
  packages/ui/package.json
  packages/ui/src/components/Dropdown/index.tsx
  packages/ui/tsconfig.json
Labels: 🐛fix

#63 [FILZ-53/trainer] feat: 트레이너 도메인 TimeOption 공통 컴포넌트 구현
  apps/trainer/components/TimeOption.tsx
  apps/trainer/package.json
  docs/storybook/package.json
  docs/storybook/stories/trainer/TimeOption.stories.tsx
  docs/storybook/tailwind.config.ts
  docs/storybook/vite.config.ts
  pnpm-lock.yaml
Labels: ✨feat

#62 [FLIZ-34/trainer] feat: Trainer 도메인 예약/일정 관리 페이지의 Calendar 컴포넌트 구현
  apps/trainer/app/global.css
  apps/trainer/app/layout.tsx
  apps/trainer/components/Calendar/DayOfWeek.tsx
  apps/trainer/components/Calendar/DaySchedule.tsx
  apps/trainer/components/Calendar/TimeBlock.tsx
  apps/trainer/components/Calendar/TimeColumn.tsx
  apps/trainer/components/Calendar/WeekSchedule.tsx
  apps/trainer/components/Calendar/index.tsx
  apps/trainer/hooks/useSyncScroll.tsx
  apps/trainer/package.json
  apps/trainer/tailwind.config.ts
  apps/trainer/types/Day.ts
  apps/trainer/utils/CalendarUtils.ts
  docs/storybook/stories/trainer/Calendar.stories.tsx
  pnpm-lock.yaml
Labels: ✨feat

#65 [FLIZ-59/config-tailwind] fix: tailwind.config.ts 에러 해결
  packages/config-tailwind/tailwind.config.ts
Labels: 🐛fix

#70 [FILZ-55/root] ci: test 자동화를 위한 CI/CD 구축
  .github/workflows/test.yml
  package.json
  turbo.json
Labels: 👷ci

#67 [FLIZ-29/trainer] feat: CalendarHintGroup 컴포넌트 구현
  apps/trainer/components/CalendarHintGroup.tsx
  docs/storybook/stories/trainer/Calendar.stories.tsx
  docs/storybook/stories/trainer/CalendarHintGroup.stories.tsx
Labels: ✨feat

#71 [FLIZ-60/ui] feat: TimeCellToggleGroup 컴포넌트 구현
  docs/storybook/stories/Badge.stories.tsx
  docs/storybook/stories/TimeCellToggleGroup.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/Badge.tsx
  packages/ui/src/components/DotWrapper.tsx
  packages/ui/src/components/TimeCellToggleGroup.tsx
  packages/ui/src/components/__tests__/TimeCellToggleGroup.spec.tsx
  packages/ui/src/components/variants/withNotification.ts
  packages/ui/src/utils/__tests__/timeCellUtils.spec.ts
  packages/ui/src/utils/dotWrapperUtils.ts
  packages/ui/src/utils/timeCellUtils.ts
  pnpm-lock.yaml
Labels: ✨feat

#66 [FLIZ-28/ui] feat: RequestResult 컴포넌트 구현
  docs/storybook/stories/RequestStatus.stories.tsx
  packages/ui/src/components/RequestStatus.tsx
  packages/ui/src/components/__tests__/RequestStatus.spec.tsx
Labels: ✨feat

#74 [FLIZ-76/config-tailwind] chore: 변경된 Typography와 동일하게 tailwind config TypoGraphy 토큰 재정의
  packages/config-tailwind/tailwind.config.ts
Labels: 📎chore

#73 [FILZ-75/ui] chore: ui 패키지 테스트 파일 path alias 적용
  packages/ui/jest.config.js
  packages/ui/src/components/__tests__/Dropdown.spec.tsx
  packages/ui/src/components/__tests__/RequestStatus.spec.tsx
  packages/ui/src/components/__tests__/Stepper.spec.tsx
  packages/ui/src/components/__tests__/TimeCellToggleGroup.spec.tsx
  packages/ui/src/hooks/__tests__/useCallbackRef.spec.tsx
  packages/ui/src/hooks/__tests__/useControllableState.spec.tsx
  packages/ui/src/utils/__tests__/DayPickerUtils.spec.ts
  packages/ui/src/utils/__tests__/timeCellUtils.spec.ts
Labels: 📎chore

#69 [FILZ-63/trainer] chore: 트레이너 도메인 테스트 환경 구축
  .github/workflows/test.yml
  apps/trainer/jest.config.ts
  apps/trainer/jest.setup.ts
  apps/trainer/package.json
  apps/trainer/tsconfig.json
  apps/trainer/utils/test/test-utils.tsx
  pnpm-lock.yaml
Labels: 📎chore

#76 [FLIZ-79/config-tailwind] chore: Typography 토큰 롤백 및 새롭운 Typography 토큰 추가
  packages/config-tailwind/tailwind.config.ts
Labels: 📎chore

#79 [FLIZ-81/ui] feat: PTHistoryItem 컴포넌트 구현
  docs/storybook/stories/PTHistory.stories.tsx
  packages/ui/src/components/PTHistoryItem.tsx
Labels: ✨feat

#84 [FLIZ-86/ui, trainer] feat: PTSchedule, PTPreference 컴포넌트 구현
  apps/trainer/components/PTSchedule.tsx
  docs/storybook/stories/PTPreference.stories.tsx
  docs/storybook/stories/trainer/PTSchedule.stories.tsx
  packages/ui/src/components/PTPreference.tsx
  packages/ui/src/utils/makeWeekSchedule.ts
Labels: ✨feat

#80 [FLIZ-80/ui] feat: Header 컴포넌트 구현
  docs/storybook/stories/Header.stories.tsx
  packages/ui/src/components/Header.tsx
Labels: ✨feat

#78 [FLIZ-62/ui] feat: ProfileHeader 컴포넌트 구현
  docs/storybook/stories/ProfileHeader.stories.tsx
  packages/ui/src/components/ChevronTrigger.tsx
  packages/ui/src/components/ProfileHeader.tsx
Labels: ✨feat

#77 [FLIZ-69/trainer] feat: 트레이너 도메인 BottomNavigation 컴포넌트 구현
  apps/trainer/components/BottomNavigation.tsx
  docs/storybook/stories/trainer/BottomNavigation.stories.tsx
  docs/storybook/tailwind.config.ts
Labels: ✨feat

#85 [FILZ-36/trainer] feat: WithBottomSheetStepper HOC 컴포넌트 구현
  apps/trainer/hoc/WithBottomSheetStepper.tsx
  apps/trainer/hoc/__tests__/WithBottomSheetStepper.spec.tsx
  apps/trainer/package.json
  docs/storybook/stories/trainer/WithBottomSheetStepper.stories.tsx
  docs/storybook/tailwind.config.ts
  packages/ui/src/components/Stepper.tsx
Labels: ✨feat

#68 [FLIZ-35/trainer] feat: 트레이너 도메인 ScheduleBottomSheet 컴포넌트 구현
  apps/trainer/components/ScheduleBottomSheet.tsx
  apps/trainer/components/TimeOptionList.tsx
  docs/storybook/stories/trainer/ScheduleBottomSheet.stories.tsx
  packages/config-eslint/base.js
  packages/ui/src/lib/DateController.ts
Labels: ✨feat

#86 [FLIZ-88/u] feat: Icon 컴포넌트 구현 및 Button에 Icon 기능 추가
  docs/storybook/stories/Button.stories.tsx
  docs/storybook/stories/Icon.stories.tsx
  packages/ui/src/components/Button.tsx
  packages/ui/src/components/Icon.tsx
Labels: ✨feat

#81 [FLIZ-78/user] feat: BottomNavigation 컴포넌트 구현
  apps/user/components/BottomNavigation.tsx
  docs/storybook/stories/user/BottomNavigation.stories.tsx
  docs/storybook/vite.config.ts
Labels: ✨feat

#75 [FLIZ-77/feat/ui] feat: 사용자 마이페이지 ProfileItem 구현
  docs/storybook/stories/ProfileItem.stories.tsx
  packages/ui/src/components/ProfileItem.tsx
Labels: ✨feat

#88 [FLIZ-98/user] style: 회원 도메인 기본 layout 스타일링
  apps/user/app/.gitkeep
  apps/user/app/global.css
  apps/user/app/layout.tsx
  apps/user/components/.gitkeep
  apps/user/components/BottomNavigation.tsx
  apps/user/package.json
  apps/user/tailwind.config.ts
  packages/config-tailwind/tailwind.config.ts
  packages/ui/src/components/Header.tsx
  pnpm-lock.yaml
Labels: 💄style

#89 [FLIZ-108/core] feat: packages/core 모듈 생성 및 해당 모듈에 axios instance, 공통 DTO 타입 정의
  packages/core/.eslintrc.js
  packages/core/package.json
  packages/core/src/api/core.ts
  packages/core/src/api/types/common.ts
  packages/core/src/utils/localStorage.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: ✨feat

#83 [FLIZ-85/trainer] feat: SearchFallback 컴포넌트 구현
  apps/trainer/components/SearchFallback.tsx
  docs/storybook/stories/trainer/SearchFallback.stories.tsx
  packages/ui/package.json
  pnpm-lock.yaml
Labels: ✨feat
