Repository Fit-Links/FitLink-FE, pull requests merged in 2025-03, with the labels that each got.

#53 [FLIZ-26/ui] feat: Popup 공통 컴포넌트 Template 구현
  docs/storybook/stories/Popup.stories.tsx
  packages/ui/src/components/Popup.tsx
Labels: ✨feat

#90 [FLIZ-112/ui] feat: DayOfTwoWeekPicker 공통 컴포넌트 구현
  docs/storybook/stories/DayOfTwoWeekPicker.stories.tsx
  packages/core/package.json
  packages/core/src/utils/generateWeeks.ts
  packages/ui/package.json
  packages/ui/src/components/DayOfTwoWeekPicker.tsx
  packages/ui/src/components/__tests__/DayOfTwoWeekPicker.spec.tsx
  pnpm-lock.yaml
Labels: ✨feat

#91 [FLIZ-94/user] feat: User 도메인 Calendar 컴포넌트 구현
  apps/user/app/global.css
  apps/user/components/Calendar/WeekRow.tsx
  apps/user/components/Calendar/index.tsx
  apps/user/package.json
  docs/storybook/package.json
  docs/storybook/stories/user/BottomNavigation.stories.tsx
  docs/storybook/stories/user/Calendar.stories.tsx
  docs/storybook/tailwind.config.ts
  packages/ui/src/components/DayPicker.tsx
  pnpm-lock.yaml
Labels: ✨feat

#92 [FILZ-114/trainer] feat: 트레이너 도메인 reservation DTO 타입 정의 및 API 함수 구현
  apps/trainer/package.json
  apps/trainer/services/core.ts
  apps/trainer/services/reservations.ts
  apps/trainer/services/types/reservations.ts
  packages/core/src/api/types/common.ts
  pnpm-lock.yaml
Labels: ✨feat

#94 [FLIZ-116/user] feat: 알림 DTO 및 API 작업
  apps/user/package.json
  apps/user/services/notification.ts
  apps/user/services/types/notification.dto.ts
  packages/core/src/api/types/common.ts
  pnpm-lock.yaml
Labels: ✨feat

#97 [FLIZ-123/trainer] feat: 트레이너 도메인 회원관리/트레이너정보 관련 카테고리 DTO 타입 정의 및 API 요청 함수 구현
  apps/trainer/constants/baseUrl.ts
  apps/trainer/services/myInformation.ts
  apps/trainer/services/reservations.ts
  apps/trainer/services/types/myInformation.dto.ts
  apps/trainer/services/types/reservations.dto.ts
  apps/trainer/services/types/userManagement.dto.ts
  apps/trainer/services/userManagement.ts
Labels: ✨feat

#93 [FLIZ-117/user] feat: 유저 도메인 reservation DTO 타입 정의 및 API 함수 구현
  apps/user/package.json
  apps/user/services/core.ts
  apps/user/services/reservations.ts
  apps/user/services/types/reservations.dto.ts
  packages/core/src/api/types/common.ts
Labels: ✨feat

#100 [FILZ-133/user] feat: 유저 도메인 Member 내 정보 관련 DTO 타입 정의 및 API 함수 구현
  apps/user/services/myInformation.ts
  apps/user/services/types/myInformation.dto.ts
  packages/core/src/api/types/common.ts
Labels: ✨feat

#101 [FLIZ-136/user] feat: user 도메인 쿼리 키 정의
  apps/user/queries/myInformation.ts
  apps/user/queries/notification.ts
  apps/user/queries/reservation.ts
  apps/user/services/myInformation.ts
  apps/user/services/reservations.ts
  apps/user/services/types/myInformation.dto.ts
Labels: ✨feat

#102 [FLIZ-137/trainer] feat: 트레이너 도메인 QueryKey Factory 구현
  apps/trainer/queries/myInformation.ts
  apps/trainer/queries/notification.ts
  apps/trainer/queries/reservation.ts
  apps/trainer/queries/userManagement.ts
  apps/trainer/services/myInformation.ts
  apps/trainer/services/reservations.ts
  apps/trainer/services/types/userManagement.dto.ts
  apps/trainer/services/userManagement.ts
Labels: ✨feat

#105 [FLIZ-151/user] feat: 회원 서비스 로그인 페이지 및 로직 구현
  apps/user/app/layout.tsx
  apps/user/app/login/_components/LoginButton/GoogleContent.tsx
  apps/user/app/login/_components/LoginButton/KakaoContent.tsx
  apps/user/app/login/_components/LoginButton/NaverContent.tsx
  apps/user/app/login/_components/LoginButton/index.tsx
  apps/user/app/login/page.tsx
  apps/user/app/register/_components/RegisterFunnel.tsx
  apps/user/app/register/_components/ResultStep.tsx
  apps/user/app/register/_hooks/useSaveTokenFromSearchParams.ts
  apps/user/app/register/_hooks/useSignupForm.ts
  apps/user/app/register/page.tsx
  apps/user/components/Providers/FooterProvider.tsx
  apps/user/components/Providers/index.tsx
  apps/user/constants/loginButton.ts
  apps/user/constants/token.ts
  apps/user/constants/url.ts
  apps/user/package.json
  apps/user/public/google_logo.png
  apps/user/public/kakao_logo.png
  apps/user/public/naver_logo.png
  apps/user/services/auth.ts
  apps/user/services/core.ts
  docs/storybook/stories/InputWithLabel.stories.tsx
  docs/storybook/stories/TimeCellToggleGroup.stories.tsx
  packages/config-tailwind/tailwind.config.ts
  packages/ui/package.json
  packages/ui/src/components/Avatar.tsx
  packages/ui/src/components/FunnelSteps/BasicInfoStep.tsx
  packages/ui/src/components/FunnelSteps/PhoneNumberStep.tsx
  packages/ui/src/components/FunnelSteps/WorkoutScheduleStep.tsx
  packages/ui/src/components/InputWithLabel/context.tsx
  packages/ui/src/components/InputWithLabel/index.tsx
  packages/ui/src/components/ProfileImagePicker.tsx
  packages/ui/src/components/RequestStatus.tsx
  packages/ui/src/components/TimeCellToggleGroup.tsx
  packages/ui/src/components/ToggleGroup.tsx
  packages/ui/src/components/WorkoutForm.tsx
  packages/ui/src/components/__tests__/TimeCellToggleGroup.spec.tsx
  packages/ui/src/utils/__tests__/timeCellUtils.spec.ts
  packages/ui/src/utils/formatDateStringFromResidentId.ts
  packages/ui/src/utils/timeCellUtils.ts
  pnpm-lock.yaml
  turbo.json
Labels: ✨feat

#106 [FLIZ-97/user] feat: 알림 페이지 구현
  apps/user/app/notification/_components/Fallback.tsx
  apps/user/app/notification/_components/NotificationContainer.tsx
  apps/user/app/notification/_components/NotificationList.tsx
  apps/user/app/notification/layout.tsx
  apps/user/app/notification/page.tsx
  docs/storybook/stories/Skeleton.stories.tsx
  packages/core/src/api/types/common.ts
  packages/ui/src/components/NotificationItem/NotificationItem.tsx
  packages/ui/src/components/NotificationItem/NotificationThumbnail.tsx
  packages/ui/src/components/Skeleton.tsx
Labels: ✨feat

#107 [FLIZ-128/config-eslint] fix: next 프로젝트 린팅 정책 수정
  apps/trainer/.eslintrc.json
  apps/user/.eslintrc.json
Labels: 🐛fix

#108 [FLIZ-176/ui] fix: Spinner 컴포넌트의 타입에러로 인한 빌드 에러 수정
  packages/ui/src/components/Spinner.tsx
Labels: 🐛fix

#109 [FLIZ-177/user] fix: 유저 도메인의 tailwind.config content의 불필요한 파일 스캔 수정
  apps/trainer/tailwind.config.ts
Labels: 🐛fix

#110 [FLIZ-187/user] fix: 유저 도메인의 tailwind.config content의 불필요한 파일 스캔 수정
  apps/user/tailwind.config.ts
Labels: 🐛fix

#111 [FLIZ-179/root] chore: turborepo 스크립트 수정
  turbo.json
Labels: 📎chore

#112 [FLIZ-180/config-eslint] chore: next.js config에 eslint-config-prettier 추가
  packages/config-eslint/next.js
Labels: 📎chore

#113 [FLIZ-181/docs] rename: storybook 배포 링크 url 수정
  docs/storybook/README.md
Labels: 🚚rename
